/**
 * GENERATED by scripts/extract-model-content.ts. Do not edit.
 *
 * A static map rather than a dynamic import, so a model referenced without a
 * file is a compile error rather than a blank page at request time.
 */

import type { ModelContent } from "@/lib/content/model-content";

import m0 from "@/content/models/galaxy-a12";
import m1 from "@/content/models/galaxy-a13";
import m2 from "@/content/models/galaxy-a14";
import m3 from "@/content/models/galaxy-a15";
import m4 from "@/content/models/galaxy-a5-2017";
import m5 from "@/content/models/galaxy-a53";
import m6 from "@/content/models/galaxy-a54";
import m7 from "@/content/models/galaxy-note-10";
import m8 from "@/content/models/galaxy-note-10-plus";
import m9 from "@/content/models/galaxy-note-2";
import m10 from "@/content/models/galaxy-note-20";
import m11 from "@/content/models/galaxy-note-20-ultra";
import m12 from "@/content/models/galaxy-note-3";
import m13 from "@/content/models/galaxy-note-4";
import m14 from "@/content/models/galaxy-note-5";
import m15 from "@/content/models/galaxy-note-8";
import m16 from "@/content/models/galaxy-note-9";
import m17 from "@/content/models/galaxy-s10";
import m18 from "@/content/models/galaxy-s10-plus";
import m19 from "@/content/models/galaxy-s10e";
import m20 from "@/content/models/galaxy-s20";
import m21 from "@/content/models/galaxy-s20-plus";
import m22 from "@/content/models/galaxy-s20-ultra";
import m23 from "@/content/models/galaxy-s21";
import m24 from "@/content/models/galaxy-s21-plus";
import m25 from "@/content/models/galaxy-s21-ultra";
import m26 from "@/content/models/galaxy-s22";
import m27 from "@/content/models/galaxy-s22-plus";
import m28 from "@/content/models/galaxy-s22-ultra";
import m29 from "@/content/models/galaxy-s23";
import m30 from "@/content/models/galaxy-s23-plus";
import m31 from "@/content/models/galaxy-s23-ultra";
import m32 from "@/content/models/galaxy-s24";
import m33 from "@/content/models/galaxy-s24-plus";
import m34 from "@/content/models/galaxy-s24-ultra";
import m35 from "@/content/models/galaxy-s25";
import m36 from "@/content/models/galaxy-s25-plus";
import m37 from "@/content/models/galaxy-s25-ultra";
import m38 from "@/content/models/galaxy-s4";
import m39 from "@/content/models/galaxy-s5";
import m40 from "@/content/models/galaxy-s5-neo";
import m41 from "@/content/models/galaxy-s6";
import m42 from "@/content/models/galaxy-s6-edge";
import m43 from "@/content/models/galaxy-s7";
import m44 from "@/content/models/galaxy-s7-edge";
import m45 from "@/content/models/galaxy-s8";
import m46 from "@/content/models/galaxy-s8-plus";
import m47 from "@/content/models/galaxy-s9";
import m48 from "@/content/models/galaxy-s9-plus";
import m49 from "@/content/models/galaxy-z-flip-3";
import m50 from "@/content/models/galaxy-z-flip-4";
import m51 from "@/content/models/galaxy-z-flip-5";
import m52 from "@/content/models/galaxy-z-flip-6";
import m53 from "@/content/models/galaxy-z-fold-3";
import m54 from "@/content/models/galaxy-z-fold-4";
import m55 from "@/content/models/galaxy-z-fold-5";
import m56 from "@/content/models/galaxy-z-fold-6";
import m57 from "@/content/models/htc-one-m7";
import m58 from "@/content/models/htc-one-m8";
import m59 from "@/content/models/htc-one-m9";
import m60 from "@/content/models/ipad-10th-gen";
import m61 from "@/content/models/ipad-2";
import m62 from "@/content/models/ipad-3";
import m63 from "@/content/models/ipad-4";
import m64 from "@/content/models/ipad-5th-gen";
import m65 from "@/content/models/ipad-6th-gen";
import m66 from "@/content/models/ipad-7th-gen";
import m67 from "@/content/models/ipad-8th-gen";
import m68 from "@/content/models/ipad-9th-gen";
import m69 from "@/content/models/ipad-air";
import m70 from "@/content/models/ipad-air-2";
import m71 from "@/content/models/ipad-air-3";
import m72 from "@/content/models/ipad-air-4";
import m73 from "@/content/models/ipad-air-5";
import m74 from "@/content/models/ipad-mini";
import m75 from "@/content/models/ipad-mini-2";
import m76 from "@/content/models/ipad-mini-3";
import m77 from "@/content/models/ipad-mini-4";
import m78 from "@/content/models/ipad-mini-5";
import m79 from "@/content/models/ipad-mini-6";
import m80 from "@/content/models/ipad-pro-10-5";
import m81 from "@/content/models/ipad-pro-11-1st-gen";
import m82 from "@/content/models/ipad-pro-11-2nd-gen";
import m83 from "@/content/models/ipad-pro-11-3rd-gen";
import m84 from "@/content/models/ipad-pro-11-4th-gen";
import m85 from "@/content/models/ipad-pro-12-9-3rd-gen";
import m86 from "@/content/models/ipad-pro-12-9-4th-gen";
import m87 from "@/content/models/ipad-pro-12-9-5th-gen";
import m88 from "@/content/models/ipad-pro-12-9-6th-gen";
import m89 from "@/content/models/ipad-pro-9-7";
import m90 from "@/content/models/iphone-11";
import m91 from "@/content/models/iphone-11-pro";
import m92 from "@/content/models/iphone-11-pro-max";
import m93 from "@/content/models/iphone-12";
import m94 from "@/content/models/iphone-12-mini";
import m95 from "@/content/models/iphone-12-pro";
import m96 from "@/content/models/iphone-12-pro-max";
import m97 from "@/content/models/iphone-13";
import m98 from "@/content/models/iphone-13-mini";
import m99 from "@/content/models/iphone-13-pro";
import m100 from "@/content/models/iphone-13-pro-max";
import m101 from "@/content/models/iphone-14";
import m102 from "@/content/models/iphone-14-plus";
import m103 from "@/content/models/iphone-14-pro";
import m104 from "@/content/models/iphone-14-pro-max";
import m105 from "@/content/models/iphone-15";
import m106 from "@/content/models/iphone-15-plus";
import m107 from "@/content/models/iphone-15-pro";
import m108 from "@/content/models/iphone-15-pro-max";
import m109 from "@/content/models/iphone-16";
import m110 from "@/content/models/iphone-16-plus";
import m111 from "@/content/models/iphone-16-pro";
import m112 from "@/content/models/iphone-16-pro-max";
import m113 from "@/content/models/iphone-4";
import m114 from "@/content/models/iphone-4s";
import m115 from "@/content/models/iphone-5";
import m116 from "@/content/models/iphone-5c";
import m117 from "@/content/models/iphone-5s";
import m118 from "@/content/models/iphone-6";
import m119 from "@/content/models/iphone-6-plus";
import m120 from "@/content/models/iphone-6s";
import m121 from "@/content/models/iphone-6s-plus";
import m122 from "@/content/models/iphone-7";
import m123 from "@/content/models/iphone-7-plus";
import m124 from "@/content/models/iphone-8";
import m125 from "@/content/models/iphone-8-plus";
import m126 from "@/content/models/iphone-se-1st-gen";
import m127 from "@/content/models/iphone-se-2nd-gen";
import m128 from "@/content/models/iphone-se-3rd-gen";
import m129 from "@/content/models/iphone-x";
import m130 from "@/content/models/iphone-xr";
import m131 from "@/content/models/iphone-xs";
import m132 from "@/content/models/iphone-xs-max";
import m133 from "@/content/models/lg-g2";
import m134 from "@/content/models/lg-g3";
import m135 from "@/content/models/lg-g4";
import m136 from "@/content/models/lg-g5";
import m137 from "@/content/models/lg-g6";
import m138 from "@/content/models/moto-g-1st-gen";
import m139 from "@/content/models/moto-g-2nd-gen";
import m140 from "@/content/models/moto-g-3rd-gen";
import m141 from "@/content/models/moto-x-play";
import m142 from "@/content/models/nexus-4";
import m143 from "@/content/models/nexus-5";
import m144 from "@/content/models/nexus-5x";
import m145 from "@/content/models/pixel-6";
import m146 from "@/content/models/pixel-6-pro";
import m147 from "@/content/models/pixel-6a";
import m148 from "@/content/models/pixel-7";
import m149 from "@/content/models/pixel-7-pro";
import m150 from "@/content/models/pixel-7a";
import m151 from "@/content/models/pixel-8";
import m152 from "@/content/models/pixel-8-pro";
import m153 from "@/content/models/pixel-8a";
import m154 from "@/content/models/pixel-9";
import m155 from "@/content/models/pixel-9-pro";

export const MODEL_CONTENT: Record<string, ModelContent> = {
  "galaxy-a12": m0,
  "galaxy-a13": m1,
  "galaxy-a14": m2,
  "galaxy-a15": m3,
  "galaxy-a5-2017": m4,
  "galaxy-a53": m5,
  "galaxy-a54": m6,
  "galaxy-note-10": m7,
  "galaxy-note-10-plus": m8,
  "galaxy-note-2": m9,
  "galaxy-note-20": m10,
  "galaxy-note-20-ultra": m11,
  "galaxy-note-3": m12,
  "galaxy-note-4": m13,
  "galaxy-note-5": m14,
  "galaxy-note-8": m15,
  "galaxy-note-9": m16,
  "galaxy-s10": m17,
  "galaxy-s10-plus": m18,
  "galaxy-s10e": m19,
  "galaxy-s20": m20,
  "galaxy-s20-plus": m21,
  "galaxy-s20-ultra": m22,
  "galaxy-s21": m23,
  "galaxy-s21-plus": m24,
  "galaxy-s21-ultra": m25,
  "galaxy-s22": m26,
  "galaxy-s22-plus": m27,
  "galaxy-s22-ultra": m28,
  "galaxy-s23": m29,
  "galaxy-s23-plus": m30,
  "galaxy-s23-ultra": m31,
  "galaxy-s24": m32,
  "galaxy-s24-plus": m33,
  "galaxy-s24-ultra": m34,
  "galaxy-s25": m35,
  "galaxy-s25-plus": m36,
  "galaxy-s25-ultra": m37,
  "galaxy-s4": m38,
  "galaxy-s5": m39,
  "galaxy-s5-neo": m40,
  "galaxy-s6": m41,
  "galaxy-s6-edge": m42,
  "galaxy-s7": m43,
  "galaxy-s7-edge": m44,
  "galaxy-s8": m45,
  "galaxy-s8-plus": m46,
  "galaxy-s9": m47,
  "galaxy-s9-plus": m48,
  "galaxy-z-flip-3": m49,
  "galaxy-z-flip-4": m50,
  "galaxy-z-flip-5": m51,
  "galaxy-z-flip-6": m52,
  "galaxy-z-fold-3": m53,
  "galaxy-z-fold-4": m54,
  "galaxy-z-fold-5": m55,
  "galaxy-z-fold-6": m56,
  "htc-one-m7": m57,
  "htc-one-m8": m58,
  "htc-one-m9": m59,
  "ipad-10th-gen": m60,
  "ipad-2": m61,
  "ipad-3": m62,
  "ipad-4": m63,
  "ipad-5th-gen": m64,
  "ipad-6th-gen": m65,
  "ipad-7th-gen": m66,
  "ipad-8th-gen": m67,
  "ipad-9th-gen": m68,
  "ipad-air": m69,
  "ipad-air-2": m70,
  "ipad-air-3": m71,
  "ipad-air-4": m72,
  "ipad-air-5": m73,
  "ipad-mini": m74,
  "ipad-mini-2": m75,
  "ipad-mini-3": m76,
  "ipad-mini-4": m77,
  "ipad-mini-5": m78,
  "ipad-mini-6": m79,
  "ipad-pro-10-5": m80,
  "ipad-pro-11-1st-gen": m81,
  "ipad-pro-11-2nd-gen": m82,
  "ipad-pro-11-3rd-gen": m83,
  "ipad-pro-11-4th-gen": m84,
  "ipad-pro-12-9-3rd-gen": m85,
  "ipad-pro-12-9-4th-gen": m86,
  "ipad-pro-12-9-5th-gen": m87,
  "ipad-pro-12-9-6th-gen": m88,
  "ipad-pro-9-7": m89,
  "iphone-11": m90,
  "iphone-11-pro": m91,
  "iphone-11-pro-max": m92,
  "iphone-12": m93,
  "iphone-12-mini": m94,
  "iphone-12-pro": m95,
  "iphone-12-pro-max": m96,
  "iphone-13": m97,
  "iphone-13-mini": m98,
  "iphone-13-pro": m99,
  "iphone-13-pro-max": m100,
  "iphone-14": m101,
  "iphone-14-plus": m102,
  "iphone-14-pro": m103,
  "iphone-14-pro-max": m104,
  "iphone-15": m105,
  "iphone-15-plus": m106,
  "iphone-15-pro": m107,
  "iphone-15-pro-max": m108,
  "iphone-16": m109,
  "iphone-16-plus": m110,
  "iphone-16-pro": m111,
  "iphone-16-pro-max": m112,
  "iphone-4": m113,
  "iphone-4s": m114,
  "iphone-5": m115,
  "iphone-5c": m116,
  "iphone-5s": m117,
  "iphone-6": m118,
  "iphone-6-plus": m119,
  "iphone-6s": m120,
  "iphone-6s-plus": m121,
  "iphone-7": m122,
  "iphone-7-plus": m123,
  "iphone-8": m124,
  "iphone-8-plus": m125,
  "iphone-se-1st-gen": m126,
  "iphone-se-2nd-gen": m127,
  "iphone-se-3rd-gen": m128,
  "iphone-x": m129,
  "iphone-xr": m130,
  "iphone-xs": m131,
  "iphone-xs-max": m132,
  "lg-g2": m133,
  "lg-g3": m134,
  "lg-g4": m135,
  "lg-g5": m136,
  "lg-g6": m137,
  "moto-g-1st-gen": m138,
  "moto-g-2nd-gen": m139,
  "moto-g-3rd-gen": m140,
  "moto-x-play": m141,
  "nexus-4": m142,
  "nexus-5": m143,
  "nexus-5x": m144,
  "pixel-6": m145,
  "pixel-6-pro": m146,
  "pixel-6a": m147,
  "pixel-7": m148,
  "pixel-7-pro": m149,
  "pixel-7a": m150,
  "pixel-8": m151,
  "pixel-8-pro": m152,
  "pixel-8a": m153,
  "pixel-9": m154,
  "pixel-9-pro": m155,
};
