/**
 * GENERATED by scripts/generate-constants.ts from the Sanity dataset.
 *
 * Phase 6.9 moved this out of Sanity under Rule 1: if the Store owner will not
 * edit it, it does not belong in a CMS. The brands and sixteen repair types
 * do not change, and having them as documents meant every price row carried
 * two references that had to be resolved on every query.
 *
 * Regenerate only if the dataset is still the source of truth. After the
 * migration it is not: this file is.
 *
 * 2026-08: LG, Motorola, HTC and Google Nexus removed on the client's
 * instruction. Their hub and model URLs 301 to /services/phone-repair in
 * next.config.ts. Nine brands became five.
 */

import type { PortableTextBlock } from "@portabletext/types";

export type BrandType = "phone" | "tablet" | "computer";

export interface BrandDef {
  slug: string;
  name: string;
  type: BrandType;
  /** Display order on the price list and the home brand strip. */
  order: number;
  active: boolean;
  /** Rendered on the brand hub. Kept as portable text so the output is unchanged. */
  intro?: PortableTextBlock[];
  seoTitle?: string;
  seoDescription?: string;
}

export const BRANDS: BrandDef[] = [
    {
      "slug": "apple-iphone",
      "name": "Apple iPhone",
      "type": "phone",
      "order": 10,
      "active": true,
      "intro": [
        {
          "_key": "brand.apple-iphone-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.apple-iphone-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz repairs every iPhone from the iPhone 4 through to the current models at 3317 17 Ave SE in Calgary. Screen replacements on the models we stock parts for are done while you wait, usually in about 30 minutes, and every price on this page includes the part and the labour. No appointment is needed. Where a model shows Call for quote, the part is ordered in and the price depends on the day's supply, so phone (403) 273-8324 and we will give you an exact figure."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "iPhone Repair Prices in Calgary",
      "seoDescription": "iPhone screen, battery and charging port repair at TechBrotherz in Calgary. Parts and labour included, most repairs done in about 30 minutes."
    },
    {
      "slug": "apple-ipad",
      "name": "Apple iPad",
      "type": "tablet",
      "order": 20,
      "active": true,
      "intro": [
        {
          "_key": "brand.apple-ipad-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.apple-ipad-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz replaces cracked iPad glass and iPad screens at 3317 17 Ave SE in Calgary. On older iPads the touch glass is a separate layer from the picture panel, so a cracked front often costs far less to fix than people expect. Bring the iPad in and we will tell you which of the two it needs before any work starts. iPad repairs take longer than phone repairs because the adhesive has to cure, so most are ready the same day rather than while you wait."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "iPad Repair Prices in Calgary",
      "seoDescription": "iPad screen and glass replacement prices at TechBrotherz in Calgary. Parts and labour included, 60-day warranty, no appointment needed."
    },
    {
      "slug": "samsung-galaxy",
      "name": "Samsung Galaxy",
      "type": "phone",
      "order": 30,
      "active": true,
      "intro": [
        {
          "_key": "brand.samsung-galaxy-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.samsung-galaxy-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz repairs Samsung Galaxy phones at 3317 17 Ave SE in Calgary, from the Galaxy S4 through to the current S and Note ranges. Galaxy screens cost more than iPhone screens because Samsung bonds the OLED panel to the frame, so the replacement part is the screen and the frame together. Every price on this page includes that part and the labour, and every repair carries a 60-day warranty. Walk in during opening hours, no appointment is needed."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "Samsung Galaxy Repair Prices in Calgary",
      "seoDescription": "Samsung Galaxy screen, battery and back glass repair at TechBrotherz in Calgary. Parts and labour included, 60-day warranty."
    },
    {
      "slug": "google-pixel",
      "name": "Google Pixel",
      "type": "phone",
      "order": 40,
      "active": true,
      "intro": [
        {
          "_key": "brand.google-pixel-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.google-pixel-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz repairs Google Pixel phones at 3317 17 Ave SE in Calgary. Pixel parts are ordered in rather than held in stock, so prices on this page show Call for quote and we confirm the figure once we know the exact model. Phone (403) 273-8324 with the model name and we will tell you the price and how soon the part can be here. Every Pixel repair carries the same 60-day warranty as the rest of our work."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "Google Pixel Repair in Calgary",
      "seoDescription": "Google Pixel screen and battery repair at TechBrotherz in Calgary. Call (403) 273-8324 for an exact quote. 60-day warranty on every repair."
    },
    {
      "slug": "laptops-desktops",
      "name": "Laptops and desktops",
      "type": "computer",
      "order": 90,
      "active": true,
      "intro": [
        {
          "_key": "brand.laptops-desktops-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.laptops-desktops-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz repairs laptops and desktop computers at 3317 17 Ave SE in Calgary. Diagnostics carry a fixed fee and tell you exactly what is wrong before you commit to a repair. Common jobs are laptop screen replacement, DC charging port replacement, keyboard replacement, Windows installation with an office suite and security software, and virus removal. Laptop repairs usually take longer than phone repairs, so most are ready the same day rather than while you wait."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "Laptop and Computer Repair Prices in Calgary",
      "seoDescription": "Laptop screen, keyboard and charging port repair, Windows installation, virus removal and tune-ups at TechBrotherz in Calgary."
    }
  ] as BrandDef[];

const BY_SLUG = new Map(BRANDS.map((brand) => [brand.slug, brand]));

export function brand(slug: string): BrandDef | undefined {
  return BY_SLUG.get(slug);
}

export function activeBrands(): BrandDef[] {
  return BRANDS.filter((entry) => entry.active).sort((a, b) => a.order - b.order);
}
