/**
 * GENERATED by scripts/generate-constants.ts from the Sanity dataset.
 *
 * Phase 6.9 moved this out of Sanity under Rule 1: if the shop owner will not
 * edit it, it does not belong in a CMS. Nine brands and sixteen repair types
 * do not change, and having them as documents meant every price row carried
 * two references that had to be resolved on every query.
 *
 * Regenerate only if the dataset is still the source of truth. After the
 * migration it is not: this file is.
 */

import type { PortableTextBlock } from "@portabletext/types";

export type BrandType = "phone" | "tablet" | "computer";

export interface BrandDef {
  slug: string;
  name: string;
  type: BrandType;
  /** Display order on the price list and the home brand strip. */
  order: number;
  active: boolean;
  /** Rendered on the brand hub. Kept as portable text so the output is unchanged. */
  intro?: PortableTextBlock[];
  seoTitle?: string;
  seoDescription?: string;
}

export const BRANDS: BrandDef[] = [
    {
      "slug": "apple-iphone",
      "name": "Apple iPhone",
      "type": "phone",
      "order": 10,
      "active": true,
      "intro": [
        {
          "_key": "brand.apple-iphone-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.apple-iphone-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz repairs every iPhone from the iPhone 4 through to the current models at 3317 17 Ave SE in Calgary. Screen replacements on the models we stock parts for are done while you wait, usually in about 30 minutes, and every price on this page includes the part and the labour. No appointment is needed. Where a model shows Call for quote, the part is ordered in and the price depends on the day's supply, so phone (403) 273-8324 and we will give you an exact figure."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "iPhone Repair Prices in Calgary",
      "seoDescription": "iPhone screen, battery and charging port repair prices at TechBrotherz in Calgary. Parts and labour included, most repairs done in about 30 minutes."
    },
    {
      "slug": "apple-ipad",
      "name": "Apple iPad",
      "type": "tablet",
      "order": 20,
      "active": true,
      "intro": [
        {
          "_key": "brand.apple-ipad-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.apple-ipad-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz replaces cracked iPad glass and iPad screens at 3317 17 Ave SE in Calgary. On older iPads the touch glass is a separate layer from the picture panel, so a cracked front often costs far less to fix than people expect. Bring the iPad in and we will tell you which of the two it needs before any work starts. iPad repairs take longer than phone repairs because the adhesive has to cure, so most are ready the same day rather than while you wait."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "iPad Repair Prices in Calgary",
      "seoDescription": "iPad screen and glass replacement prices at TechBrotherz in Calgary. Parts and labour included, 60-day warranty, no appointment needed."
    },
    {
      "slug": "samsung-galaxy",
      "name": "Samsung Galaxy",
      "type": "phone",
      "order": 30,
      "active": true,
      "intro": [
        {
          "_key": "brand.samsung-galaxy-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.samsung-galaxy-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz repairs Samsung Galaxy phones at 3317 17 Ave SE in Calgary, from the Galaxy S4 through to the current S and Note ranges. Galaxy screens cost more than iPhone screens because Samsung bonds the OLED panel to the frame, so the replacement part is the screen and the frame together. Every price on this page includes that part and the labour, and every repair carries a 60-day warranty. Walk in during opening hours, no appointment is needed."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "Samsung Galaxy Repair Prices in Calgary",
      "seoDescription": "Samsung Galaxy screen, battery and back glass repair prices at TechBrotherz in Calgary. Parts and labour included, 60-day warranty."
    },
    {
      "slug": "google-pixel",
      "name": "Google Pixel",
      "type": "phone",
      "order": 40,
      "active": true,
      "intro": [
        {
          "_key": "brand.google-pixel-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.google-pixel-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz repairs Google Pixel phones at 3317 17 Ave SE in Calgary. Pixel parts are ordered in rather than held in stock, so prices on this page show Call for quote and we confirm the figure once we know the exact model. Phone (403) 273-8324 with the model name and we will tell you the price and how soon the part can be here. Every Pixel repair carries the same 60-day warranty as the rest of our work."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "Google Pixel Repair in Calgary",
      "seoDescription": "Google Pixel screen and battery repair at TechBrotherz in Calgary. Call (403) 273-8324 for an exact quote. 60-day warranty on every repair."
    },
    {
      "slug": "google-nexus",
      "name": "Google Nexus",
      "type": "phone",
      "order": 50,
      "active": true,
      "intro": [
        {
          "_key": "brand.google-nexus-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.google-nexus-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz still repairs Google Nexus phones at 3317 17 Ave SE in Calgary, long after most shops have stopped stocking the parts. Screen replacements for the Nexus 4, Nexus 5 and Nexus 5X are priced on this page and include the part and the labour. These are older phones, so it is worth weighing the repair against the value of the handset, and we will give you an honest view on that before any work starts."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "Google Nexus Screen Repair in Calgary",
      "seoDescription": "Nexus 4, Nexus 5 and Nexus 5X screen replacement at TechBrotherz in Calgary. Parts and labour included, 60-day warranty."
    },
    {
      "slug": "lg",
      "name": "LG",
      "type": "phone",
      "order": 60,
      "active": true,
      "intro": [
        {
          "_key": "brand.lg-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.lg-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz replaces LG phone screens at 3317 17 Ave SE in Calgary, covering the G2 through to the G6. LG stopped making phones in 2021, so parts come from remaining stock and we will confirm availability when you call. Every price on this page includes the part and the labour and carries a 60-day warranty. Phone (403) 273-8324 before travelling if you want to be certain the part for your model is here."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "LG Phone Screen Repair in Calgary",
      "seoDescription": "LG G2, G3, G4, G5 and G6 screen replacement at TechBrotherz in Calgary. Parts and labour included, 60-day warranty."
    },
    {
      "slug": "motorola",
      "name": "Motorola",
      "type": "phone",
      "order": 70,
      "active": true,
      "intro": [
        {
          "_key": "brand.motorola-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.motorola-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz replaces Motorola screens at 3317 17 Ave SE in Calgary, including the Moto G in its first three generations and the Moto X Play. Motorola phones are usually straightforward to open, so screen replacements are among the quicker repairs we do. Each price on this page includes the part and the labour and carries a 60-day warranty. Walk in during opening hours or phone (403) 273-8324 to check the part is in stock."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "Motorola Screen Repair in Calgary",
      "seoDescription": "Moto G and Moto X Play screen replacement at TechBrotherz in Calgary. Parts and labour included, 60-day warranty."
    },
    {
      "slug": "htc",
      "name": "HTC",
      "type": "phone",
      "order": 80,
      "active": true,
      "intro": [
        {
          "_key": "brand.htc-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.htc-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz replaces HTC One screens at 3317 17 Ave SE in Calgary, covering the M7, M8 and M9. The HTC One series has a bonded aluminium body, so the screen assembly is replaced as one unit rather than in layers. Each price on this page includes that part and the labour and carries a 60-day warranty. Phone (403) 273-8324 with your model before travelling, since HTC parts are getting harder to source."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "HTC Screen Repair in Calgary",
      "seoDescription": "HTC One M7, M8 and M9 screen replacement at TechBrotherz in Calgary. Parts and labour included, 60-day warranty."
    },
    {
      "slug": "laptops-desktops",
      "name": "Laptops and desktops",
      "type": "computer",
      "order": 90,
      "active": true,
      "intro": [
        {
          "_key": "brand.laptops-desktops-b0",
          "_type": "block",
          "children": [
            {
              "_key": "brand.laptops-desktops-s0",
              "_type": "span",
              "marks": [],
              "text": "TechBrotherz repairs laptops and desktop computers at 3317 17 Ave SE in Calgary. Diagnostics are $24.99 and tell you exactly what is wrong before you commit to a repair. Common jobs are laptop screen replacement from $120, DC charging port replacement at $109.99, keyboard replacement between $69.99 and $149.99, Windows installation with Office and security at $44.99, and virus removal at $34.99. Laptop repairs usually take longer than phone repairs, so most are ready the same day rather than while you wait."
            }
          ],
          "markDefs": [],
          "style": "normal"
        }
      ],
      "seoTitle": "Laptop and Computer Repair Prices in Calgary",
      "seoDescription": "Laptop screen, keyboard and charging port repair, Windows installation, virus removal and tune-ups at TechBrotherz in Calgary."
    }
  ] as BrandDef[];

const BY_SLUG = new Map(BRANDS.map((brand) => [brand.slug, brand]));

export function brand(slug: string): BrandDef | undefined {
  return BY_SLUG.get(slug);
}

export function activeBrands(): BrandDef[] {
  return BRANDS.filter((entry) => entry.active).sort((a, b) => a.order - b.order);
}
