/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

// Source: schema.json
export type Location = {
  _id: string;
  _type: "location";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  city?: string;
  slug?: Slug;
  kind?: "city" | "neighbourhood";
  province?: string;
  isPrimary?: boolean;
  neighbourhoods?: Array<string>;
  distanceKm?: number;
  driveTimeMinutes?: number;
  landmarks?: Array<string>;
  routeDescription?: string;
  transitDescription?: string;
  commonRepairs?: Array<string>;
  intro?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  mapEmbedUrl?: string;
  parent?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "location";
  };
  order?: number;
  published?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Testimonial = {
  _id: string;
  _type: "testimonial";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  rating?: number;
  text?: string;
  device?: string;
  source?: "Google" | "Facebook" | "In person" | "Email";
  sourceUrl?: string;
  date?: string;
  verified?: boolean;
};

export type ServicePage = {
  _id: string;
  _type: "servicePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  serviceType?:
    | "phone-repair"
    | "iphone-repair"
    | "samsung-repair"
    | "ipad-repair"
    | "tablet-repair"
    | "laptop-repair"
    | "computer-repair"
    | "phone-unlocking"
    | "password-reset"
    | "virus-removal";
  parentService?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "servicePage";
  };
  quickAnswer?: string;
  heroHeadline?: string;
  heroSubcopy?: string;
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  benefits?: Array<string>;
  processSteps?: Array<
    {
      _key: string;
    } & ProcessStep
  >;
  faqs?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "faq";
  }>;
  relatedModels?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "deviceModel";
  }>;
  relatedGuides?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "guide";
  }>;
  localPagePath?: string;
  published?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Guide = {
  _id: string;
  _type: "guide";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  excerpt?: string;
  quickAnswer?: string;
  heroImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  body?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  author?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "author";
  };
  publishedAt?: string;
  updatedAt?: string;
  schemaType?: "Article" | "HowTo" | "FAQPage";
  howToSteps?: Array<
    {
      _key: string;
    } & HowToStep
  >;
  readingMinutes?: number;
  faqs?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "faq";
  }>;
  relatedServices?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "servicePage";
  }>;
  relatedModels?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "deviceModel";
  }>;
  relatedLocations?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "location";
  }>;
  relatedGuides?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "guide";
  }>;
  published?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Author = {
  _id: string;
  _type: "author";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  role?: string;
  bio?: string;
  photo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  credentials?: Array<string>;
  yearsExperience?: number;
  published?: boolean;
};

export type Faq = {
  _id: string;
  _type: "faq";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  question?: string;
  plainAnswer?: string;
  answer?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  category?:
    | "pricing"
    | "warranty"
    | "turnaround"
    | "walkin"
    | "parts"
    | "data"
    | "unlocking"
    | "iphone"
    | "samsung"
    | "ipad"
    | "computer"
    | "location"
    | "business";
  appliesToServices?: Array<string>;
  appliesToModels?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "deviceModel";
  }>;
  appliesToLocations?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "location";
  }>;
  featured?: boolean;
  order?: number;
  published?: boolean;
};

export type UnlockingService = {
  _id: string;
  _type: "unlockingService";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  carrier?: string;
  deviceType?: "phone" | "tablet";
  price?: number;
  turnaround?: string;
  notes?: string;
  order?: number;
  published?: boolean;
};

export type FlatService = {
  _id: string;
  _type: "flatService";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  price?: number;
  priceFrom?: boolean;
  priceTo?: number;
  quoteOnly?: boolean;
  category?: "computer" | "software" | "other";
  description?: string;
  includes?: Array<string>;
  turnaroundMinutes?: number;
  order?: number;
  needsVerification?: boolean;
  published?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type PriceEntry = {
  _id: string;
  _type: "priceEntry";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  model?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "deviceModel";
  };
  repairType?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "repairType";
  };
  price?: number;
  quoteOnly?: boolean;
  partGrade?: "OEM" | "Premium" | "Standard" | "Aftermarket";
  turnaroundMinutes?: number;
  warrantyDays?: number;
  inStock?: boolean;
  priceGroup?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "priceGroup";
  };
  note?: string;
  needsVerification?: boolean;
};

export type PriceGroup = {
  _id: string;
  _type: "priceGroup";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  models?: Array<{
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    _key: string;
    [internalGroqTypeReferenceTo]?: "deviceModel";
  }>;
  note?: string;
};

export type RepairType = {
  _id: string;
  _type: "repairType";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  shortDescription?: string;
  longDescription?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  estimatedMinutes?: number;
  appliesTo?: Array<string>;
  symptoms?: Array<string>;
  icon?: string;
  order?: number;
  published?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type DeviceModel = {
  _id: string;
  _type: "deviceModel";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  brand?: {
    _ref: string;
    _type: "reference";
    _weak?: boolean;
    [internalGroqTypeReferenceTo]?: "brand";
  };
  deviceType?: "phone" | "tablet" | "laptop" | "desktop";
  releaseYear?: number;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  aliases?: Array<string>;
  commonIssues?: Array<string>;
  intro?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  verdict?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  repairNotes?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  lastSupportedOs?: string;
  stillReceivesUpdates?: boolean;
  popular?: boolean;
  discontinued?: boolean;
  published?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Brand = {
  _id: string;
  _type: "brand";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  name?: string;
  slug?: Slug;
  logo?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  type?: "phone" | "tablet" | "computer";
  intro?: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "normal" | "h2" | "h3" | "blockquote";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  >;
  order?: number;
  active?: boolean;
  published?: boolean;
  seoTitle?: string;
  seoDescription?: string;
  ogImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  noIndex?: boolean;
};

export type Redirect = {
  _id: string;
  _type: "redirect";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  from?: string;
  to?: string;
  permanent?: boolean;
};

export type ReviewSummary = {
  _id: string;
  _type: "reviewSummary";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  enabled?: boolean;
  ratingValue?: number;
  reviewCount?: number;
  source?: string;
  sourceUrl?: string;
  lastVerified?: string;
};

export type Navigation = {
  _id: string;
  _type: "navigation";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  header?: Array<{
    label?: string;
    href?: string;
    _type: "navLink";
    _key: string;
  }>;
  footerColumns?: Array<{
    heading?: string;
    links?: Array<{
      label?: string;
      href?: string;
      _type: "navLink";
      _key: string;
    }>;
    _type: "footerColumn";
    _key: string;
  }>;
};

export type SiteSettings = {
  _id: string;
  _type: "siteSettings";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  brandName?: string;
  legalName?: string;
  tagline?: string;
  street?: string;
  city?: string;
  region?: string;
  regionCode?: string;
  postalCode?: string;
  country?: string;
  geo?: GeoPoint;
  phone?: string;
  phoneRaw?: string;
  email?: string;
  googleMapsUrl?: string;
  googleBusinessUrl?: string;
  socialLinks?: Array<
    {
      _key: string;
    } & SocialLink
  >;
  hours?: Array<
    {
      _key: string;
    } & OpeningHours
  >;
  warrantyDays?: number;
  appointmentPolicy?: string;
  typicalWaitMinutes?: number;
  priceDisclaimer?: string;
  paymentAccepted?: Array<string>;
  foundedYear?: number;
  defaultOgImage?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
  gaId?: string;
  gscVerification?: string;
  announcementBar?: AnnouncementBar;
};

export type RichText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3" | "blockquote";
      listItem?: "bullet" | "number";
      markDefs?: Array<{
        href?: string;
        isExternal?: boolean;
        _type: "link";
        _key: string;
      }>;
      level?: number;
      _type: "block";
      _key: string;
    }
  | {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
      _key: string;
    }
>;

export type ProcessStep = {
  _type: "processStep";
  title?: string;
  description?: string;
};

export type HowToStep = {
  _type: "howToStep";
  name?: string;
  text?: string;
  image?: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  };
};

export type AnnouncementBar = {
  _type: "announcementBar";
  active?: boolean;
  text?: string;
  link?: string;
};

export type SocialLink = {
  _type: "socialLink";
  platform?: "Facebook" | "Instagram" | "X" | "YouTube" | "TikTok" | "Google Business Profile";
  url?: string;
};

export type GeoPoint = {
  _type: "geoPoint";
  lat?: number;
  lng?: number;
};

export type OpeningHours = {
  _type: "openingHours";
  day?: "Monday" | "Tuesday" | "Wednesday" | "Thursday" | "Friday" | "Saturday" | "Sunday";
  closed?: boolean;
  open?: string;
  close?: string;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type AllSanitySchemaTypes =
  | Location
  | Testimonial
  | ServicePage
  | Guide
  | Author
  | Faq
  | UnlockingService
  | FlatService
  | PriceEntry
  | PriceGroup
  | RepairType
  | DeviceModel
  | Brand
  | Redirect
  | ReviewSummary
  | Navigation
  | SiteSettings
  | RichText
  | ProcessStep
  | HowToStep
  | AnnouncementBar
  | SocialLink
  | GeoPoint
  | OpeningHours
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageHotspot
  | SanityImageCrop
  | SanityFileAsset
  | SanityImageAsset
  | SanityImageMetadata
  | Geopoint
  | Slug
  | SanityAssetSourceData;
export declare const internalGroqTypeReferenceTo: unique symbol;
// Source: ./sanity/queries/catalogue.ts
// Variable: BRANDS_QUERY
// Query: *[_type == "brand" && (published == true || $draft) && !(_id in path("drafts.**")) && active == true] | order(order asc, name asc){    _id,    _updatedAt,    name,    "slug": slug.current,    type,    logo,    intro,    seoDescription,    "modelCount": count(*[_type == "deviceModel" && brand._ref == ^._id && published == true]),    "oldestModel": *[_type == "deviceModel" && brand._ref == ^._id && published == true]      | order(releaseYear asc)[0].name,    "newestModel": *[_type == "deviceModel" && brand._ref == ^._id && published == true]      | order(releaseYear desc)[0].name,    "fromPrice": math::min(      *[_type == "priceEntry" && defined(price) &&        model->brand._ref == ^._id && model->published == true].price    )  }
export type BRANDS_QUERYResult = Array<{
  _id: string;
  _updatedAt: string;
  name: string | null;
  slug: string | null;
  type: "computer" | "phone" | "tablet" | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  intro: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  seoDescription: string | null;
  modelCount: number;
  oldestModel: string | null;
  newestModel: string | null;
  fromPrice: number | null;
}>;
// Variable: BRAND_BY_SLUG_QUERY
// Query: *[_type == "brand" && slug.current == $slug && (published == true || $draft) && !(_id in path("drafts.**"))][0]{    _id,    _updatedAt,    name,    "slug": slug.current,    type,    logo,    intro,    seoTitle,    seoDescription,    ogImage,    noIndex  }
export type BRAND_BY_SLUG_QUERYResult = {
  _id: string;
  _updatedAt: string;
  name: string | null;
  slug: string | null;
  type: "computer" | "phone" | "tablet" | null;
  logo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  intro: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  noIndex: boolean | null;
} | null;
// Variable: MODELS_BY_BRAND_QUERY
// Query: *[_type == "deviceModel" && brand->slug.current == $brandSlug && (published == true || $draft) && !(_id in path("drafts.**"))]    | order(releaseYear desc, name asc){        _id,  name,  "slug": slug.current,  deviceType,  releaseYear,  popular,  "brandName": brand->name,  "brandSlug": brand->slug.current,    "fromPrice": math::min(*[_type == "priceEntry" && model._ref == ^._id && defined(price)].price)    }
export type MODELS_BY_BRAND_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  deviceType: "desktop" | "laptop" | "phone" | "tablet" | null;
  releaseYear: number | null;
  popular: boolean | null;
  brandName: string | null;
  brandSlug: string | null;
  fromPrice: number | null;
}>;
// Variable: MODEL_BY_SLUG_QUERY
// Query: *[_type == "deviceModel" && slug.current == $slug && (published == true || $draft) && !(_id in path("drafts.**"))][0]{    _id,    _updatedAt,    name,    "slug": slug.current,    deviceType,    releaseYear,    image,    aliases,    commonIssues,    intro,    verdict,    repairNotes,    lastSupportedOs,    stillReceivesUpdates,    popular,    discontinued,    seoTitle,    seoDescription,    ogImage,    noIndex,    "brand": brand->{ _id, name, "slug": slug.current, type },    "priceGroup": *[_type == "priceGroup" && references(^._id)][0]{      name,      note,      "models": models[]->{ name, "slug": slug.current, "brandSlug": brand->slug.current }    },      "prices": *[_type == "priceEntry" && model._ref == ^._id] | order(repairType->order asc, repairType->name asc){      _id,  price,  quoteOnly,  partGrade,  turnaroundMinutes,  warrantyDays,  inStock,  note,  needsVerification,  "repair": repairType->{    _id,    name,    "slug": slug.current,    shortDescription,    estimatedMinutes,    order  },  "sharedWith": priceGroup->{ name, note }  },      "fromPrice": math::min(*[_type == "priceEntry" && model._ref == ^._id && defined(price)].price)  }
export type MODEL_BY_SLUG_QUERYResult = {
  _id: string;
  _updatedAt: string;
  name: string | null;
  slug: string | null;
  deviceType: "desktop" | "laptop" | "phone" | "tablet" | null;
  releaseYear: number | null;
  image: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  aliases: Array<string> | null;
  commonIssues: Array<string> | null;
  intro: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  verdict: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  repairNotes: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  lastSupportedOs: string | null;
  stillReceivesUpdates: boolean | null;
  popular: boolean | null;
  discontinued: boolean | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  noIndex: boolean | null;
  brand: {
    _id: string;
    name: string | null;
    slug: string | null;
    type: "computer" | "phone" | "tablet" | null;
  } | null;
  priceGroup: {
    name: string | null;
    note: string | null;
    models: Array<{
      name: string | null;
      slug: string | null;
      brandSlug: string | null;
    }> | null;
  } | null;
  prices: Array<{
    _id: string;
    price: number | null;
    quoteOnly: boolean | null;
    partGrade: "Aftermarket" | "OEM" | "Premium" | "Standard" | null;
    turnaroundMinutes: number | null;
    warrantyDays: number | null;
    inStock: boolean | null;
    note: string | null;
    needsVerification: boolean | null;
    repair: {
      _id: string;
      name: string | null;
      slug: string | null;
      shortDescription: string | null;
      estimatedMinutes: number | null;
      order: number | null;
    } | null;
    sharedWith: {
      name: string | null;
      note: string | null;
    } | null;
  }>;
  fromPrice: number | null;
} | null;
// Variable: BRAND_HUB_QUERY
// Query: *[_type == "brand" && slug.current == $slug && (published == true || $draft) && !(_id in path("drafts.**"))][0]{    _id,    _updatedAt,    name,    "slug": slug.current,    type,    intro,    seoTitle,    seoDescription,    ogImage,    noIndex,    "models": *[_type == "deviceModel" && brand._ref == ^._id && (published == true || $draft) && !(_id in path("drafts.**"))]      | order(releaseYear desc, name asc){        _id,        name,        "slug": slug.current,        deviceType,        releaseYear,        stillReceivesUpdates,          "fromPrice": math::min(*[_type == "priceEntry" && model._ref == ^._id && defined(price)].price),        "repairCount": count(*[_type == "priceEntry" && model._ref == ^._id]),        "pricedCount": count(*[_type == "priceEntry" && model._ref == ^._id && defined(price)])      },    "awaitingPrices": *[_type == "deviceModel" && brand._ref == ^._id && published != true]      | order(releaseYear desc, name asc){        name,        releaseYear      },    "repairTypes": *[_type == "repairType" && (published == true || $draft) && !(_id in path("drafts.**"))] | order(order asc){      name,      "slug": slug.current,      shortDescription,      appliesTo,      estimatedMinutes    }  }
export type BRAND_HUB_QUERYResult = {
  _id: string;
  _updatedAt: string;
  name: string | null;
  slug: string | null;
  type: "computer" | "phone" | "tablet" | null;
  intro: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  noIndex: boolean | null;
  models: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    deviceType: "desktop" | "laptop" | "phone" | "tablet" | null;
    releaseYear: number | null;
    stillReceivesUpdates: boolean | null;
    fromPrice: number | null;
    repairCount: number;
    pricedCount: number;
  }>;
  awaitingPrices: Array<{
    name: string | null;
    releaseYear: number | null;
  }>;
  repairTypes: Array<{
    name: string | null;
    slug: string | null;
    shortDescription: string | null;
    appliesTo: Array<string> | null;
    estimatedMinutes: number | null;
  }>;
} | null;
// Variable: MODEL_SUMMARIES_QUERY
// Query: *[_type == "deviceModel" && (published == true || $draft) && !(_id in path("drafts.**")) && count(*[_type == "priceEntry" && model._ref == ^._id]) > 0]    | order(brand->order asc, releaseYear desc, name asc){      _id,      name,      "slug": slug.current,      deviceType,      releaseYear,      "brandName": brand->name,      "brandSlug": brand->slug.current,      "repairCount": count(*[_type == "priceEntry" && model._ref == ^._id]),      "pricedCount": count(*[_type == "priceEntry" && model._ref == ^._id && defined(price)]),      "fromPrice": math::min(*[_type == "priceEntry" && model._ref == ^._id && defined(price)].price),      "toPrice": math::max(*[_type == "priceEntry" && model._ref == ^._id && defined(price)].price)    }
export type MODEL_SUMMARIES_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  deviceType: "desktop" | "laptop" | "phone" | "tablet" | null;
  releaseYear: number | null;
  brandName: string | null;
  brandSlug: string | null;
  repairCount: number;
  pricedCount: number;
  fromPrice: number | null;
  toPrice: number | null;
}>;
// Variable: POPULAR_MODELS_QUERY
// Query: *[_type == "deviceModel" && popular == true && (published == true || $draft) && !(_id in path("drafts.**"))]    | order(releaseYear desc, name asc)[0...$limit]{        _id,  name,  "slug": slug.current,  deviceType,  releaseYear,  popular,  "brandName": brand->name,  "brandSlug": brand->slug.current,    "fromPrice": math::min(*[_type == "priceEntry" && model._ref == ^._id && defined(price)].price)    }
export type POPULAR_MODELS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  deviceType: "desktop" | "laptop" | "phone" | "tablet" | null;
  releaseYear: number | null;
  popular: boolean | null;
  brandName: string | null;
  brandSlug: string | null;
  fromPrice: number | null;
}>;
// Variable: ALL_PRICED_MODELS_QUERY
// Query: *[_type == "deviceModel" && (published == true || $draft) && !(_id in path("drafts.**")) && count(*[_type == "priceEntry" && model._ref == ^._id]) > 0]    | order(brand->order asc, releaseYear desc, name asc){      _id,      name,      "slug": slug.current,      deviceType,      releaseYear,      "brandName": brand->name,      "brandSlug": brand->slug.current,        "prices": *[_type == "priceEntry" && model._ref == ^._id] | order(repairType->order asc, repairType->name asc){      _id,  price,  quoteOnly,  partGrade,  turnaroundMinutes,  warrantyDays,  inStock,  note,  needsVerification,  "repair": repairType->{    _id,    name,    "slug": slug.current,    shortDescription,    estimatedMinutes,    order  },  "sharedWith": priceGroup->{ name, note }  }    }
export type ALL_PRICED_MODELS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  deviceType: "desktop" | "laptop" | "phone" | "tablet" | null;
  releaseYear: number | null;
  brandName: string | null;
  brandSlug: string | null;
  prices: Array<{
    _id: string;
    price: number | null;
    quoteOnly: boolean | null;
    partGrade: "Aftermarket" | "OEM" | "Premium" | "Standard" | null;
    turnaroundMinutes: number | null;
    warrantyDays: number | null;
    inStock: boolean | null;
    note: string | null;
    needsVerification: boolean | null;
    repair: {
      _id: string;
      name: string | null;
      slug: string | null;
      shortDescription: string | null;
      estimatedMinutes: number | null;
      order: number | null;
    } | null;
    sharedWith: {
      name: string | null;
      note: string | null;
    } | null;
  }>;
}>;
// Variable: RELATED_MODELS_QUERY
// Query: *[_type == "deviceModel" && (published == true || $draft) && !(_id in path("drafts.**")) && _id != $modelId && brand._ref == $brandId]    | order(        select(          coalesce(releaseYear, 0) >= $releaseYear => coalesce(releaseYear, 0) - $releaseYear,          $releaseYear - coalesce(releaseYear, 0)        ) asc,        name asc      )[0...3]{        _id,  name,  "slug": slug.current,  deviceType,  releaseYear,  popular,  "brandName": brand->name,  "brandSlug": brand->slug.current,    "fromPrice": math::min(*[_type == "priceEntry" && model._ref == ^._id && defined(price)].price)    }
export type RELATED_MODELS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  deviceType: "desktop" | "laptop" | "phone" | "tablet" | null;
  releaseYear: number | null;
  popular: boolean | null;
  brandName: string | null;
  brandSlug: string | null;
  fromPrice: number | null;
}>;
// Variable: MODEL_SEARCH_INDEX_QUERY
// Query: *[_type == "deviceModel" && (published == true || $draft) && !(_id in path("drafts.**"))] | order(name asc){    name,    "slug": slug.current,    "brandSlug": brand->slug.current,    aliases  }
export type MODEL_SEARCH_INDEX_QUERYResult = Array<{
  name: string | null;
  slug: string | null;
  brandSlug: string | null;
  aliases: Array<string> | null;
}>;
// Variable: REPAIR_TYPES_QUERY
// Query: *[_type == "repairType" && (published == true || $draft) && !(_id in path("drafts.**"))] | order(order asc, name asc){    _id,    _updatedAt,    name,    "slug": slug.current,    shortDescription,    estimatedMinutes,    appliesTo,    symptoms,    icon,    order  }
export type REPAIR_TYPES_QUERYResult = Array<{
  _id: string;
  _updatedAt: string;
  name: string | null;
  slug: string | null;
  shortDescription: string | null;
  estimatedMinutes: number | null;
  appliesTo: Array<string> | null;
  symptoms: Array<string> | null;
  icon: string | null;
  order: number | null;
}>;
// Variable: REPAIR_TYPE_BY_SLUG_QUERY
// Query: *[_type == "repairType" && slug.current == $slug && (published == true || $draft) && !(_id in path("drafts.**"))][0]{    _id,    _updatedAt,    name,    "slug": slug.current,    shortDescription,    longDescription,    estimatedMinutes,    appliesTo,    symptoms,    seoTitle,    seoDescription,    ogImage,    noIndex,    "examplePrices": *[_type == "priceEntry" && repairType._ref == ^._id && defined(price)]      | order(price asc)[0...12]{          _id,  price,  quoteOnly,  partGrade,  turnaroundMinutes,  warrantyDays,  inStock,  note,  needsVerification,  "repair": repairType->{    _id,    name,    "slug": slug.current,    shortDescription,    estimatedMinutes,    order  },  "sharedWith": priceGroup->{ name, note },        "modelName": model->name,        "modelSlug": model->slug.current,        "brandSlug": model->brand->slug.current      }  }
export type REPAIR_TYPE_BY_SLUG_QUERYResult = {
  _id: string;
  _updatedAt: string;
  name: string | null;
  slug: string | null;
  shortDescription: string | null;
  longDescription: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  estimatedMinutes: number | null;
  appliesTo: Array<string> | null;
  symptoms: Array<string> | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  noIndex: boolean | null;
  examplePrices: Array<{
    _id: string;
    price: number | null;
    quoteOnly: boolean | null;
    partGrade: "Aftermarket" | "OEM" | "Premium" | "Standard" | null;
    turnaroundMinutes: number | null;
    warrantyDays: number | null;
    inStock: boolean | null;
    note: string | null;
    needsVerification: boolean | null;
    repair: {
      _id: string;
      name: string | null;
      slug: string | null;
      shortDescription: string | null;
      estimatedMinutes: number | null;
      order: number | null;
    } | null;
    sharedWith: {
      name: string | null;
      note: string | null;
    } | null;
    modelName: string | null;
    modelSlug: string | null;
    brandSlug: string | null;
  }>;
} | null;
// Variable: FLAT_SERVICES_QUERY
// Query: *[_type == "flatService" && (published == true || $draft) && !(_id in path("drafts.**"))] | order(order asc, name asc){    _id,    _updatedAt,    name,    "slug": slug.current,    price,    priceFrom,    priceTo,    quoteOnly,    category,    description,    includes,    turnaroundMinutes,    needsVerification  }
export type FLAT_SERVICES_QUERYResult = Array<{
  _id: string;
  _updatedAt: string;
  name: string | null;
  slug: string | null;
  price: number | null;
  priceFrom: boolean | null;
  priceTo: number | null;
  quoteOnly: boolean | null;
  category: "computer" | "other" | "software" | null;
  description: string | null;
  includes: Array<string> | null;
  turnaroundMinutes: number | null;
  needsVerification: boolean | null;
}>;
// Variable: UNLOCKING_QUERY
// Query: *[_type == "unlockingService" && (published == true || $draft) && !(_id in path("drafts.**"))] | order(order asc, carrier asc){    _id,    _updatedAt,    carrier,    deviceType,    price,    turnaround,    notes  }
export type UNLOCKING_QUERYResult = Array<{
  _id: string;
  _updatedAt: string;
  carrier: string | null;
  deviceType: "phone" | "tablet" | null;
  price: number | null;
  turnaround: string | null;
  notes: string | null;
}>;

// Source: ./sanity/queries/content.ts
// Variable: GLOBAL_FAQS_QUERY
// Query: *[_type == "faq" && (published == true || $draft) && !(_id in path("drafts.**")) && featured == true] | order(order asc)[0...$limit]{      _id,  question,  plainAnswer,  answer,  category,  featured,  order  }
export type GLOBAL_FAQS_QUERYResult = Array<{
  _id: string;
  question: string | null;
  plainAnswer: string | null;
  answer: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  category:
    | "business"
    | "computer"
    | "data"
    | "ipad"
    | "iphone"
    | "location"
    | "parts"
    | "pricing"
    | "samsung"
    | "turnaround"
    | "unlocking"
    | "walkin"
    | "warranty"
    | null;
  featured: boolean | null;
  order: number | null;
}>;
// Variable: FAQS_FOR_QUERY
// Query: *[_type == "faq" && (published == true || $draft) && !(_id in path("drafts.**")) && (      ($service != null && $service in appliesToServices) ||      ($model != null && $model in appliesToModels[]._ref) ||      ($location != null && $location in appliesToLocations[]._ref)    )] | order(order asc)[0...$limit]{        _id,  question,  plainAnswer,  answer,  category,  featured,  order    }
export type FAQS_FOR_QUERYResult = Array<{
  _id: string;
  question: string | null;
  plainAnswer: string | null;
  answer: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  category:
    | "business"
    | "computer"
    | "data"
    | "ipad"
    | "iphone"
    | "location"
    | "parts"
    | "pricing"
    | "samsung"
    | "turnaround"
    | "unlocking"
    | "walkin"
    | "warranty"
    | null;
  featured: boolean | null;
  order: number | null;
}>;
// Variable: FAQS_BY_CATEGORY_QUERY
// Query: *[_type == "faq" && (published == true || $draft) && !(_id in path("drafts.**")) && category == $category] | order(order asc){      _id,  question,  plainAnswer,  answer,  category,  featured,  order  }
export type FAQS_BY_CATEGORY_QUERYResult = Array<{
  _id: string;
  question: string | null;
  plainAnswer: string | null;
  answer: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  category:
    | "business"
    | "computer"
    | "data"
    | "ipad"
    | "iphone"
    | "location"
    | "parts"
    | "pricing"
    | "samsung"
    | "turnaround"
    | "unlocking"
    | "walkin"
    | "warranty"
    | null;
  featured: boolean | null;
  order: number | null;
}>;
// Variable: ALL_FAQS_QUERY
// Query: *[_type == "faq" && (published == true || $draft) && !(_id in path("drafts.**"))] | order(category asc, order asc){      _id,  question,  plainAnswer,  answer,  category,  featured,  order  }
export type ALL_FAQS_QUERYResult = Array<{
  _id: string;
  question: string | null;
  plainAnswer: string | null;
  answer: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  category:
    | "business"
    | "computer"
    | "data"
    | "ipad"
    | "iphone"
    | "location"
    | "parts"
    | "pricing"
    | "samsung"
    | "turnaround"
    | "unlocking"
    | "walkin"
    | "warranty"
    | null;
  featured: boolean | null;
  order: number | null;
}>;
// Variable: GUIDES_QUERY
// Query: *[_type == "guide" && (published == true || $draft) && !(_id in path("drafts.**"))] | order(publishedAt desc){    _id,    _updatedAt,    title,    "slug": slug.current,    excerpt,    quickAnswer,    heroImage,    publishedAt,    updatedAt,    readingMinutes,    "author": author->{ name, role }  }
export type GUIDES_QUERYResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  quickAnswer: string | null;
  heroImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  publishedAt: string | null;
  updatedAt: string | null;
  readingMinutes: number | null;
  author: {
    name: string | null;
    role: string | null;
  } | null;
}>;
// Variable: GUIDE_BY_SLUG_QUERY
// Query: *[_type == "guide" && slug.current == $slug && (published == true || $draft) && !(_id in path("drafts.**"))][0]{    _id,    _updatedAt,    title,    "slug": slug.current,    excerpt,    quickAnswer,    heroImage,    body,    publishedAt,    updatedAt,    schemaType,    howToSteps,    readingMinutes,    seoTitle,    seoDescription,    ogImage,    noIndex,    "author": author->{ name, role, bio, photo, credentials, yearsExperience },    "faqs": faqs[]->{   _id,  question,  plainAnswer,  answer,  category,  featured,  order },    "relatedServices": relatedServices[]->{ title, "slug": slug.current, serviceType },    "relatedModels": relatedModels[]->{   _id,  name,  "slug": slug.current,  deviceType,  releaseYear,  popular,  "brandName": brand->name,  "brandSlug": brand->slug.current,    "fromPrice": math::min(*[_type == "priceEntry" && model._ref == ^._id && defined(price)].price) },    "relatedLocations": relatedLocations[]->{ city, "slug": slug.current, kind },    "relatedGuides": relatedGuides[]->{ title, "slug": slug.current, excerpt }  }
export type GUIDE_BY_SLUG_QUERYResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  excerpt: string | null;
  quickAnswer: string | null;
  heroImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  publishedAt: string | null;
  updatedAt: string | null;
  schemaType: "Article" | "FAQPage" | "HowTo" | null;
  howToSteps: Array<
    {
      _key: string;
    } & HowToStep
  > | null;
  readingMinutes: number | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  noIndex: boolean | null;
  author: {
    name: string | null;
    role: string | null;
    bio: string | null;
    photo: {
      asset?: {
        _ref: string;
        _type: "reference";
        _weak?: boolean;
        [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
      };
      media?: unknown;
      hotspot?: SanityImageHotspot;
      crop?: SanityImageCrop;
      _type: "image";
    } | null;
    credentials: Array<string> | null;
    yearsExperience: number | null;
  } | null;
  faqs: Array<{
    _id: string;
    question: string | null;
    plainAnswer: string | null;
    answer: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h2" | "h3" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            isExternal?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }
    > | null;
    category:
      | "business"
      | "computer"
      | "data"
      | "ipad"
      | "iphone"
      | "location"
      | "parts"
      | "pricing"
      | "samsung"
      | "turnaround"
      | "unlocking"
      | "walkin"
      | "warranty"
      | null;
    featured: boolean | null;
    order: number | null;
  }> | null;
  relatedServices: Array<{
    title: string | null;
    slug: string | null;
    serviceType:
      | "computer-repair"
      | "ipad-repair"
      | "iphone-repair"
      | "laptop-repair"
      | "password-reset"
      | "phone-repair"
      | "phone-unlocking"
      | "samsung-repair"
      | "tablet-repair"
      | "virus-removal"
      | null;
  }> | null;
  relatedModels: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    deviceType: "desktop" | "laptop" | "phone" | "tablet" | null;
    releaseYear: number | null;
    popular: boolean | null;
    brandName: string | null;
    brandSlug: string | null;
    fromPrice: number | null;
  }> | null;
  relatedLocations: Array<{
    city: string | null;
    slug: string | null;
    kind: "city" | "neighbourhood" | null;
  }> | null;
  relatedGuides: Array<{
    title: string | null;
    slug: string | null;
    excerpt: string | null;
  }> | null;
} | null;
// Variable: SERVICE_PAGE_BY_SLUG_QUERY
// Query: *[_type == "servicePage" && slug.current == $slug && (published == true || $draft) && !(_id in path("drafts.**"))][0]{    _id,    _updatedAt,    title,    "slug": slug.current,    serviceType,    quickAnswer,    heroHeadline,    heroSubcopy,    body,    benefits,    processSteps,    localPagePath,    seoTitle,    seoDescription,    ogImage,    noIndex,    "parentService": parentService->{ title, "slug": slug.current },    "faqs": faqs[]->{   _id,  question,  plainAnswer,  answer,  category,  featured,  order },    "relatedModels": relatedModels[]->{   _id,  name,  "slug": slug.current,  deviceType,  releaseYear,  popular,  "brandName": brand->name,  "brandSlug": brand->slug.current,    "fromPrice": math::min(*[_type == "priceEntry" && model._ref == ^._id && defined(price)].price) },    "relatedGuides": relatedGuides[]->{ title, "slug": slug.current, excerpt }  }
export type SERVICE_PAGE_BY_SLUG_QUERYResult = {
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  serviceType:
    | "computer-repair"
    | "ipad-repair"
    | "iphone-repair"
    | "laptop-repair"
    | "password-reset"
    | "phone-repair"
    | "phone-unlocking"
    | "samsung-repair"
    | "tablet-repair"
    | "virus-removal"
    | null;
  quickAnswer: string | null;
  heroHeadline: string | null;
  heroSubcopy: string | null;
  body: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  benefits: Array<string> | null;
  processSteps: Array<
    {
      _key: string;
    } & ProcessStep
  > | null;
  localPagePath: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  noIndex: boolean | null;
  parentService: {
    title: string | null;
    slug: string | null;
  } | null;
  faqs: Array<{
    _id: string;
    question: string | null;
    plainAnswer: string | null;
    answer: Array<
      | {
          children?: Array<{
            marks?: Array<string>;
            text?: string;
            _type: "span";
            _key: string;
          }>;
          style?: "blockquote" | "h2" | "h3" | "normal";
          listItem?: "bullet" | "number";
          markDefs?: Array<{
            href?: string;
            isExternal?: boolean;
            _type: "link";
            _key: string;
          }>;
          level?: number;
          _type: "block";
          _key: string;
        }
      | {
          asset?: {
            _ref: string;
            _type: "reference";
            _weak?: boolean;
            [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
          };
          media?: unknown;
          hotspot?: SanityImageHotspot;
          crop?: SanityImageCrop;
          _type: "image";
          _key: string;
        }
    > | null;
    category:
      | "business"
      | "computer"
      | "data"
      | "ipad"
      | "iphone"
      | "location"
      | "parts"
      | "pricing"
      | "samsung"
      | "turnaround"
      | "unlocking"
      | "walkin"
      | "warranty"
      | null;
    featured: boolean | null;
    order: number | null;
  }> | null;
  relatedModels: Array<{
    _id: string;
    name: string | null;
    slug: string | null;
    deviceType: "desktop" | "laptop" | "phone" | "tablet" | null;
    releaseYear: number | null;
    popular: boolean | null;
    brandName: string | null;
    brandSlug: string | null;
    fromPrice: number | null;
  }> | null;
  relatedGuides: Array<{
    title: string | null;
    slug: string | null;
    excerpt: string | null;
  }> | null;
} | null;
// Variable: SERVICE_PAGES_QUERY
// Query: *[_type == "servicePage" && (published == true || $draft) && !(_id in path("drafts.**"))] | order(title asc){    _id,    _updatedAt,    title,    "slug": slug.current,    serviceType,    heroSubcopy,    "parentSlug": parentService->slug.current  }
export type SERVICE_PAGES_QUERYResult = Array<{
  _id: string;
  _updatedAt: string;
  title: string | null;
  slug: string | null;
  serviceType:
    | "computer-repair"
    | "ipad-repair"
    | "iphone-repair"
    | "laptop-repair"
    | "password-reset"
    | "phone-repair"
    | "phone-unlocking"
    | "samsung-repair"
    | "tablet-repair"
    | "virus-removal"
    | null;
  heroSubcopy: string | null;
  parentSlug: string | null;
}>;
// Variable: TESTIMONIALS_QUERY
// Query: *[_type == "testimonial" && verified == true] | order(date desc)[0...$limit]{    _id,    name,    rating,    text,    device,    source,    sourceUrl,    date  }
export type TESTIMONIALS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  rating: number | null;
  text: string | null;
  device: string | null;
  source: "Email" | "Facebook" | "Google" | "In person" | null;
  sourceUrl: string | null;
  date: string | null;
}>;
// Variable: AUTHORS_QUERY
// Query: *[_type == "author" && (published == true || $draft) && !(_id in path("drafts.**"))] | order(name asc){    _id,    name,    "slug": slug.current,    role,    bio,    photo,    credentials,    yearsExperience  }
export type AUTHORS_QUERYResult = Array<{
  _id: string;
  name: string | null;
  slug: string | null;
  role: string | null;
  bio: string | null;
  photo: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  credentials: Array<string> | null;
  yearsExperience: number | null;
}>;

// Source: ./sanity/queries/locations.ts
// Variable: LOCATIONS_QUERY
// Query: *[_type == "location" && (published == true || $draft) && !(_id in path("drafts.**"))] | order(isPrimary desc, order asc, city asc){    _id,    _updatedAt,    city,    "slug": slug.current,    kind,    province,    isPrimary,    distanceKm,    driveTimeMinutes,    neighbourhoods,    routeDescription,    transitDescription,    "parentSlug": parent->slug.current  }
export type LOCATIONS_QUERYResult = Array<{
  _id: string;
  _updatedAt: string;
  city: string | null;
  slug: string | null;
  kind: "city" | "neighbourhood" | null;
  province: string | null;
  isPrimary: boolean | null;
  distanceKm: number | null;
  driveTimeMinutes: number | null;
  neighbourhoods: Array<string> | null;
  routeDescription: string | null;
  transitDescription: string | null;
  parentSlug: string | null;
}>;
// Variable: LOCATION_BY_SLUG_QUERY
// Query: *[_type == "location" && slug.current == $slug && (published == true || $draft) && !(_id in path("drafts.**"))][0]{    _id,    _updatedAt,    city,    "slug": slug.current,    kind,    province,    isPrimary,    neighbourhoods,    distanceKm,    driveTimeMinutes,    landmarks,    routeDescription,    transitDescription,    commonRepairs,    intro,    mapEmbedUrl,    seoTitle,    seoDescription,    ogImage,    noIndex,    "parent": parent->{ city, "slug": slug.current, kind },    "children": *[_type == "location" && parent._ref == ^._id && (published == true || $draft) && !(_id in path("drafts.**"))] | order(order asc){      city, "slug": slug.current, driveTimeMinutes, distanceKm    }  }
export type LOCATION_BY_SLUG_QUERYResult = {
  _id: string;
  _updatedAt: string;
  city: string | null;
  slug: string | null;
  kind: "city" | "neighbourhood" | null;
  province: string | null;
  isPrimary: boolean | null;
  neighbourhoods: Array<string> | null;
  distanceKm: number | null;
  driveTimeMinutes: number | null;
  landmarks: Array<string> | null;
  routeDescription: string | null;
  transitDescription: string | null;
  commonRepairs: Array<string> | null;
  intro: Array<
    | {
        children?: Array<{
          marks?: Array<string>;
          text?: string;
          _type: "span";
          _key: string;
        }>;
        style?: "blockquote" | "h2" | "h3" | "normal";
        listItem?: "bullet" | "number";
        markDefs?: Array<{
          href?: string;
          isExternal?: boolean;
          _type: "link";
          _key: string;
        }>;
        level?: number;
        _type: "block";
        _key: string;
      }
    | {
        asset?: {
          _ref: string;
          _type: "reference";
          _weak?: boolean;
          [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
        };
        media?: unknown;
        hotspot?: SanityImageHotspot;
        crop?: SanityImageCrop;
        _type: "image";
        _key: string;
      }
  > | null;
  mapEmbedUrl: string | null;
  seoTitle: string | null;
  seoDescription: string | null;
  ogImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  noIndex: boolean | null;
  parent: {
    city: string | null;
    slug: string | null;
    kind: "city" | "neighbourhood" | null;
  } | null;
  children: Array<{
    city: string | null;
    slug: string | null;
    driveTimeMinutes: number | null;
    distanceKm: number | null;
  }>;
} | null;
// Variable: NEAREST_LOCATIONS_QUERY
// Query: *[_type == "location" && (published == true || $draft) && !(_id in path("drafts.**")) && _id != $locationId && kind == "neighbourhood"]    | order(coalesce(distanceKm, 999) asc)[0...3]{      city,      "slug": slug.current,      distanceKm,      driveTimeMinutes    }
export type NEAREST_LOCATIONS_QUERYResult = Array<{
  city: string | null;
  slug: string | null;
  distanceKm: number | null;
  driveTimeMinutes: number | null;
}>;

// Source: ./sanity/queries/site.ts
// Variable: SITE_SETTINGS_QUERY
// Query: *[_type == "siteSettings"][0]{    _id,    _updatedAt,    brandName,    legalName,    tagline,    street,    city,    region,    regionCode,    postalCode,    country,    geo,    phone,    phoneRaw,    email,    googleMapsUrl,    googleBusinessUrl,    socialLinks,    hours,    warrantyDays,    appointmentPolicy,    typicalWaitMinutes,    priceDisclaimer,    paymentAccepted,    foundedYear,    defaultOgImage,    gaId,    gscVerification,    announcementBar  }
export type SITE_SETTINGS_QUERYResult = {
  _id: string;
  _updatedAt: string;
  brandName: string | null;
  legalName: string | null;
  tagline: string | null;
  street: string | null;
  city: string | null;
  region: string | null;
  regionCode: string | null;
  postalCode: string | null;
  country: string | null;
  geo: GeoPoint | null;
  phone: string | null;
  phoneRaw: string | null;
  email: string | null;
  googleMapsUrl: string | null;
  googleBusinessUrl: string | null;
  socialLinks: Array<
    {
      _key: string;
    } & SocialLink
  > | null;
  hours: Array<
    {
      _key: string;
    } & OpeningHours
  > | null;
  warrantyDays: number | null;
  appointmentPolicy: string | null;
  typicalWaitMinutes: number | null;
  priceDisclaimer: string | null;
  paymentAccepted: Array<string> | null;
  foundedYear: number | null;
  defaultOgImage: {
    asset?: {
      _ref: string;
      _type: "reference";
      _weak?: boolean;
      [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
    };
    media?: unknown;
    hotspot?: SanityImageHotspot;
    crop?: SanityImageCrop;
    _type: "image";
  } | null;
  gaId: string | null;
  gscVerification: string | null;
  announcementBar: AnnouncementBar | null;
} | null;
// Variable: NAVIGATION_QUERY
// Query: *[_type == "navigation"][0]{    header[]{ label, href },    footerColumns[]{ heading, links[]{ label, href } }  }
export type NAVIGATION_QUERYResult = {
  header: Array<{
    label: string | null;
    href: string | null;
  }> | null;
  footerColumns: Array<{
    heading: string | null;
    links: Array<{
      label: string | null;
      href: string | null;
    }> | null;
  }> | null;
} | null;
// Variable: REVIEW_SUMMARY_QUERY
// Query: *[_type == "reviewSummary"][0]{    enabled,    ratingValue,    reviewCount,    source,    sourceUrl,    lastVerified  }
export type REVIEW_SUMMARY_QUERYResult = {
  enabled: boolean | null;
  ratingValue: number | null;
  reviewCount: number | null;
  source: string | null;
  sourceUrl: string | null;
  lastVerified: string | null;
} | null;
// Variable: REDIRECTS_QUERY
// Query: *[_type == "redirect"]{ from, to, permanent }
export type REDIRECTS_QUERYResult = Array<{
  from: string | null;
  to: string | null;
  permanent: boolean | null;
}>;

// Source: ./sanity/queries/sitemap.ts
// Variable: ALL_SLUGS_FOR_SITEMAP_QUERY
// Query: {  "brands": *[_type == "brand" && (published == true || $draft) && !(_id in path("drafts.**")) && active == true && noIndex != true]{    "slug": slug.current, _updatedAt  },  "models": *[_type == "deviceModel" && (published == true || $draft) && !(_id in path("drafts.**")) && noIndex != true]{    "slug": slug.current,    "brandSlug": brand->slug.current,    _updatedAt  },  "servicePages": *[_type == "servicePage" && (published == true || $draft) && !(_id in path("drafts.**")) && noIndex != true]{    "slug": slug.current,    "parentSlug": parentService->slug.current,    _updatedAt  },  "guides": *[_type == "guide" && (published == true || $draft) && !(_id in path("drafts.**")) && noIndex != true]{    "slug": slug.current, _updatedAt  },  "locations": *[_type == "location" && (published == true || $draft) && !(_id in path("drafts.**")) && noIndex != true]{    "slug": slug.current,    kind,    "parentSlug": parent->slug.current,    _updatedAt  }}
export type ALL_SLUGS_FOR_SITEMAP_QUERYResult = {
  brands: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
  models: Array<{
    slug: string | null;
    brandSlug: string | null;
    _updatedAt: string;
  }>;
  servicePages: Array<{
    slug: string | null;
    parentSlug: string | null;
    _updatedAt: string;
  }>;
  guides: Array<{
    slug: string | null;
    _updatedAt: string;
  }>;
  locations: Array<{
    slug: string | null;
    kind: "city" | "neighbourhood" | null;
    parentSlug: string | null;
    _updatedAt: string;
  }>;
};
// Variable: MODEL_PARAMS_QUERY
// Query: *[_type == "deviceModel" && (published == true || $draft) && !(_id in path("drafts.**"))]{    "slug": slug.current,    "brandSlug": brand->slug.current  }
export type MODEL_PARAMS_QUERYResult = Array<{
  slug: string | null;
  brandSlug: string | null;
}>;
// Variable: BRAND_PARAMS_QUERY
// Query: *[_type == "brand" && (published == true || $draft) && !(_id in path("drafts.**")) && active == true]{ "slug": slug.current }
export type BRAND_PARAMS_QUERYResult = Array<{
  slug: string | null;
}>;
