/**
 * GENERATED by scripts/export-content.ts from the Sanity dataset.
 *
 * The question bank. Scoping rules in CLAUDE.md Section 8.8 decide which of
 * these reach which page, and lib/faq/scoping.ts enforces them.
 *
 * This file is now the source of truth. Edit it directly: there is no dataset
 * behind it and no import step to re-run.
 */

import type { FaqDoc } from "./types";

export const FAQ_DOCS: FaqDoc[] = [
  {
    "_id": "faq.common-ipad-repairs-apple-vs-third-party",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.common-ipad-repairs-apple-vs-third-party-b0",
        "children": [
          {
            "_key": "faq.common-ipad-repairs-apple-vs-third-party-s0",
            "marks": [],
            "text": "The three most common iPad repairs are cracked front glass, a battery that no longer holds a charge, and a charging port that has stopped seating the cable properly. Cracked glass is by far the most common of the three.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.common-ipad-repairs-apple-vs-third-party-b1",
        "children": [
          {
            "_key": "faq.common-ipad-repairs-apple-vs-third-party-s1",
            "marks": [],
            "text": "At TechBrotherz in Calgary, iPad glass replacement is quoted per model, because the part differs across the range: an iPad 2, 3 or 4 is the smallest job, an iPad Mini 3 the largest of the older models, and the iPad Air and Mini 2 sit between them. Each quote includes the part and the labour and carries a 60-day warranty.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.common-ipad-repairs-apple-vs-third-party-b2",
        "children": [
          {
            "_key": "faq.common-ipad-repairs-apple-vs-third-party-s2",
            "marks": [],
            "text": "Apple publishes its own iPad service pricing on apple.com, and the figure depends on the model and on whether the tablet is covered by AppleCare. We would rather point you at Apple's published page than quote a number for them. The practical differences are that a third-party shop is usually cheaper on older models, does not require an appointment, and can often do the work the same day.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "ipad",
    "featured": true,
    "order": 50,
    "plainAnswer": "The most common iPad repairs are cracked glass, a worn battery and a failed charging port. At TechBrotherz in Calgary, iPad glass replacement is quoted per model, and the quote is free and agreed before any work starts. Apple publishes its own iPad service pricing on apple.com, and it varies by model and by whether you have AppleCare.",
    "published": true,
    "question": "What are the most common iPad repairs and their average costs at Canadian Apple stores versus third-party repair shops?"
  },
  {
    "_id": "faq.cracked-screen-vs-broken-lcd",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.cracked-screen-vs-broken-lcd-b0",
        "children": [
          {
            "_key": "faq.cracked-screen-vs-broken-lcd-s0",
            "marks": [],
            "text": "A cracked screen means the outer glass is broken while the picture underneath is still perfect. A broken LCD means the display panel itself has failed, which shows up as black ink-like patches spreading across the screen, coloured blotches, or lines running down it.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.cracked-screen-vs-broken-lcd-b1",
        "children": [
          {
            "_key": "faq.cracked-screen-vs-broken-lcd-s1",
            "marks": [],
            "text": "A digitizer is the touch-sensitive glass layer above the LCD. It is what registers your finger. On most modern phones the glass, the digitizer and the display panel are bonded into one assembly, so all three are replaced together and the price is the same whichever layer broke.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.cracked-screen-vs-broken-lcd-b2",
        "children": [
          {
            "_key": "faq.cracked-screen-vs-broken-lcd-s2",
            "marks": [],
            "text": "On many older tablets the layers are separate, so a cracked front can be fixed by replacing only the glass, which costs far less. Bring the device to 3317 17 Ave SE and we will tell you which of the two yours needs before quoting.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "parts",
    "featured": true,
    "order": 190,
    "plainAnswer": "A cracked screen means the outer glass is broken but the picture is still normal. A broken LCD means the display panel underneath has failed, showing black ink-like patches, coloured blotches or lines. A digitizer is the touch-sensitive glass layer above the LCD.",
    "published": true,
    "question": "What is the difference between a cracked screen and a broken LCD?"
  },
  {
    "_id": "faq.do-i-need-an-appointment",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.do-i-need-an-appointment-b0",
        "children": [
          {
            "_key": "faq.do-i-need-an-appointment-s0",
            "marks": [],
            "text": "No appointment is needed. TechBrotherz is a walk-in store at 3317 17 Ave SE in Calgary, and we start on your device when you arrive.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.do-i-need-an-appointment-b1",
        "children": [
          {
            "_key": "faq.do-i-need-an-appointment-s1",
            "marks": [],
            "text": "Most phone screen and battery repairs take about 30 minutes, so you can wait while the work is done. If you want to be certain the part for your exact model is in stock before you travel, phone (403) 273-8324 first and we will check.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "walkin",
    "featured": true,
    "order": 60,
    "plainAnswer": "No. TechBrotherz is a walk-in store at 3317 17 Ave SE in Calgary. Come in during opening hours and we start on the spot. Most phone screen and battery repairs are finished in about 30 minutes while you wait. There is no booking system and no queue to join in advance.",
    "published": true,
    "question": "Do I need an appointment for a phone repair in Calgary?"
  },
  {
    "_id": "faq.do-prices-include-parts-and-labour",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.do-prices-include-parts-and-labour-b0",
        "children": [
          {
            "_key": "faq.do-prices-include-parts-and-labour-s0",
            "marks": [],
            "text": "Yes. Every quote from TechBrotherz includes both the part and the labour, so the figure you are given is the figure you pay before tax.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.do-prices-include-parts-and-labour-b1",
        "children": [
          {
            "_key": "faq.do-prices-include-parts-and-labour-s1",
            "marks": [],
            "text": "There is no separate bench fee on a phone repair and no diagnostic charge to look at a phone. Computer diagnostics carry a fixed fee that is deducted from the repair if you go ahead, and it is quoted to you before any work starts so there is never a surprise on the bill.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "pricing",
    "featured": true,
    "order": 90,
    "plainAnswer": "Yes. Every quote includes both the part and the labour, so the figure you are given is the figure you pay. There is no separate bench fee on phone repairs and no diagnostic charge for a phone. Computer diagnostics carry a fixed fee, quoted before any work starts and deducted from the repair if you go ahead.",
    "published": true,
    "question": "Do your prices include the part and the labour?"
  },
  {
    "_id": "faq.do-you-need-my-passcode",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.do-you-need-my-passcode-b0",
        "children": [
          {
            "_key": "faq.do-you-need-my-passcode-s0",
            "marks": [],
            "text": "For most repairs we need to unlock the device at the end to test the work. Checking touch across every part of a new screen, confirming a camera focuses, or testing a microphone all require the phone to be unlocked.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.do-you-need-my-passcode-b1",
        "children": [
          {
            "_key": "faq.do-you-need-my-passcode-s1",
            "marks": [],
            "text": "Most repairs take about 30 minutes, so you are welcome to stay in the store and unlock the phone yourself for testing. If you would rather not share a passcode at all, say so when you drop the device off and we will test everything we can without it and explain what we could not check.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "data",
    "featured": false,
    "order": 120,
    "plainAnswer": "For most repairs we need to unlock the device to test it afterwards, for example to check touch across a new screen or to confirm a camera works. You can stay in the store while we do it. If you would rather not share the passcode, tell us and we will test what we can without it.",
    "published": true,
    "question": "Do you need my passcode to repair my phone?"
  },
  {
    "_id": "faq.do-you-repair-water-damage",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.do-you-repair-water-damage-b0",
        "children": [
          {
            "_key": "faq.do-you-repair-water-damage-s0",
            "marks": [],
            "text": "Sometimes, and speed matters more than anything else. Corrosion keeps spreading inside the phone for as long as the liquid is in there, so a phone brought in the same day has a much better chance than one brought in a week later.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.do-you-repair-water-damage-b1",
        "children": [
          {
            "_key": "faq.do-you-repair-water-damage-s1",
            "marks": [],
            "text": "Two things to do first: turn the phone off and leave it off, and do not plug it in to charge. Putting a wet phone in rice does not work and wastes the time that actually matters.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.do-you-repair-water-damage-b2",
        "children": [
          {
            "_key": "faq.do-you-repair-water-damage-s2",
            "marks": [],
            "text": "Liquid damage is the one repair no honest shop will promise, because the outcome depends on what liquid got in, how far it travelled and how long it sat there. We will open the phone, clean the corrosion and tell you what we find before charging you for anything beyond that.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "turnaround",
    "featured": false,
    "order": 200,
    "plainAnswer": "Sometimes, and the sooner the better. Do not charge a wet phone and do not put it in rice. Turn it off, bring it to 3317 17 Ave SE, and we will open it and clean the corrosion. Liquid damage is the one repair no shop can promise, because the damage depends on what got in and where.",
    "published": true,
    "question": "Can you fix a phone that has been in water?"
  },
  {
    "_id": "faq.find-reputable-ipad-repair-canada",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.find-reputable-ipad-repair-canada-b0",
        "children": [
          {
            "_key": "faq.find-reputable-ipad-repair-canada-s0",
            "marks": [],
            "text": "Look for four things. A shop that publishes its prices in writing, so you know the figure before you hand the tablet over. A warranty stated as a number of days rather than as a vague promise. A real street address you can walk into and return to if something goes wrong. And a shop willing to tell you when a repair is not worth buying.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.find-reputable-ipad-repair-canada-b1",
        "children": [
          {
            "_key": "faq.find-reputable-ipad-repair-canada-s1",
            "marks": [],
            "text": "Ask two questions before agreeing to any work: what exactly is included in the price, and what happens if the part fails next month. A shop that answers both plainly is usually a shop that will stand behind the work.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.find-reputable-ipad-repair-canada-b2",
        "children": [
          {
            "_key": "faq.find-reputable-ipad-repair-canada-s2",
            "marks": [],
            "text": "TechBrotherz quotes every repair free before any work starts, includes the part and the labour in each figure, and covers every repair for 60 days. The store is at 3317 17 Ave SE in Calgary and you can walk in during opening hours without an appointment.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "ipad",
    "featured": true,
    "order": 30,
    "plainAnswer": "Look for four things: a firm figure given in writing before you hand the tablet over, a warranty stated in days rather than vaguely, a real street address you can walk into, and a shop willing to tell you when a repair is not worth buying. TechBrotherz quotes every repair before any work starts and warrants every repair for 60 days.",
    "published": true,
    "question": "How do I find a reputable iPad repair store in Canada that offers fair pricing?"
  },
  {
    "_id": "faq.how-long-does-a-repair-take",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.how-long-does-a-repair-take-b0",
        "children": [
          {
            "_key": "faq.how-long-does-a-repair-take-s0",
            "marks": [],
            "text": "Most phone screen and battery replacements take about 30 minutes, and you are welcome to wait in the store while the work is done. Charging port, camera and button repairs usually take 30 to 45 minutes.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.how-long-does-a-repair-take-b1",
        "children": [
          {
            "_key": "faq.how-long-does-a-repair-take-s1",
            "marks": [],
            "text": "Laptop and computer work takes longer. A laptop screen or charging port replacement means stripping the machine down and testing it before reassembly, so those are usually ready the same day rather than while you wait. Windows installation with Office and security takes about two hours.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "turnaround",
    "featured": true,
    "order": 70,
    "plainAnswer": "Most phone screen and battery replacements take about 30 minutes while you wait. Charging port and camera repairs usually take 30 to 45 minutes. Laptop repairs take longer, usually the same day rather than while you wait, because the machine has to be stripped down and tested.",
    "published": true,
    "question": "How long does a phone repair take at TechBrotherz?"
  },
  {
    "_id": "faq.how-much-to-unlock-a-phone",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.how-much-to-unlock-a-phone-b0",
        "children": [
          {
            "_key": "faq.how-much-to-unlock-a-phone-s0",
            "marks": [],
            "text": "TechBrotherz unlocks phones locked to any Canadian carrier, usually the same day. That covers Rogers, Bell, Telus, Fido, Koodo, Virgin, Freedom, Chatr and Public Mobile.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.how-much-to-unlock-a-phone-b1",
        "children": [
          {
            "_key": "faq.how-much-to-unlock-a-phone-s1",
            "marks": [],
            "text": "Worth knowing first: since December 2017 the CRTC Wireless Code has required Canadian carriers to unlock phones free of charge on request, so it is always worth asking your carrier before paying anyone. People come to us when the carrier will not do it, when the phone was bought secondhand and is still locked, or when they want it done while they wait.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.how-much-to-unlock-a-phone-b2",
        "children": [
          {
            "_key": "faq.how-much-to-unlock-a-phone-s2",
            "marks": [],
            "text": "Unlocking does not erase your data and does not void the manufacturer warranty. A phone reported lost or stolen is on the national blacklist and cannot be unlocked by anyone, including us. We will tell you straight away if that is the case.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "unlocking",
    "featured": true,
    "order": 140,
    "plainAnswer": "TechBrotherz unlocks phones locked to any Canadian carrier, usually the same day. Since 2017 the CRTC Wireless Code has required Canadian carriers to unlock phones free on request, so ask your carrier first. Come to us if they will not, or if the phone came from someone else.",
    "published": true,
    "question": "How much does it cost to unlock a cell phone in Calgary?"
  },
  {
    "_id": "faq.ipad-screen-repair-vs-new-canada",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.ipad-screen-repair-vs-new-canada-b0",
        "children": [
          {
            "_key": "faq.ipad-screen-repair-vs-new-canada-s0",
            "marks": [],
            "text": "At TechBrotherz in Calgary, iPad glass replacement is quoted per model. An iPad 2, 3 or 4 is the smallest job, an iPad Mini or Mini 2 a slightly bigger one, an iPad Air bigger again, and an iPad Mini 3 the largest of the older models because its Touch ID sensor has to be transferred. Every quote includes the part and the labour and carries a 60-day warranty.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.ipad-screen-repair-vs-new-canada-b1",
        "children": [
          {
            "_key": "faq.ipad-screen-repair-vs-new-canada-s1",
            "marks": [],
            "text": "A new entry-level iPad in Canada costs several hundred dollars before tax, and a Pro model costs well over a thousand. Against that, a glass repair on an older iPad is normally the cheaper option by a wide margin, and it keeps the apps, photos and files already on the tablet.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.ipad-screen-repair-vs-new-canada-b2",
        "children": [
          {
            "_key": "faq.ipad-screen-repair-vs-new-canada-s2",
            "marks": [],
            "text": "The comparison changes on newer iPads where the glass is laminated to the display panel, because the two have to be replaced together as one part. Bring the iPad to 3317 17 Ave SE and we will tell you which kind yours is and what it costs before any work starts.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "ipad",
    "featured": true,
    "order": 10,
    "plainAnswer": "At TechBrotherz in Calgary, iPad glass replacement is quoted per model, and the quote is free and agreed before any work starts. An iPad 2, 3 or 4 is the smallest job and an iPad Mini 3 the largest of the older models. A new entry-level iPad costs several hundred dollars, so a glass repair is normally the cheaper option by a wide margin.",
    "published": true,
    "question": "How much does it typically cost to repair a cracked iPad screen in Canada compared to buying a new one?"
  },
  {
    "_id": "faq.is-unlocking-legal-in-canada",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.is-unlocking-legal-in-canada-b0",
        "children": [
          {
            "_key": "faq.is-unlocking-legal-in-canada-s0",
            "marks": [],
            "text": "Yes. Unlocking a phone you own is legal in Canada. Since December 2017 the CRTC Wireless Code has gone further and required Canadian carriers to unlock devices free of charge on request, and to sell new phones unlocked.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.is-unlocking-legal-in-canada-b1",
        "children": [
          {
            "_key": "faq.is-unlocking-legal-in-canada-s1",
            "marks": [],
            "text": "Unlocking is not the same thing as jailbreaking or rooting. Unlocking only removes the carrier restriction so the phone accepts another network's SIM. Jailbreaking modifies the operating system itself, and that can affect the manufacturer warranty and the phone's security.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "unlocking",
    "featured": false,
    "order": 150,
    "plainAnswer": "Yes. Unlocking a phone you own is legal in Canada, and since December 2017 the CRTC Wireless Code has required carriers to unlock devices free on request. Unlocking is not the same as jailbreaking, which changes the phone's operating system and can affect the manufacturer warranty.",
    "published": true,
    "question": "Is unlocking a phone legal in Canada?"
  },
  {
    "_id": "faq.repair-or-replace-ipad-canada",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.repair-or-replace-ipad-canada-b0",
        "children": [
          {
            "_key": "faq.repair-or-replace-ipad-canada-s0",
            "marks": [],
            "text": "Four things decide it. First, the repair price against what a replacement actually costs you, not the list price of the newest model. Second, whether the iPad still receives iPadOS updates, because an iPad that has stopped getting security updates has a limited useful life no matter how good the screen is.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.repair-or-replace-ipad-canada-b1",
        "children": [
          {
            "_key": "faq.repair-or-replace-ipad-canada-s1",
            "marks": [],
            "text": "Third, the battery. An iPad more than five years old has usually lost a large share of its original capacity, so a screen repair on its own may leave you with a tablet that still will not last a day. Fourth, whether anything else is already going: a charging port that only works at an angle, a camera that will not focus, buttons that stick.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.repair-or-replace-ipad-canada-b2",
        "children": [
          {
            "_key": "faq.repair-or-replace-ipad-canada-s2",
            "marks": [],
            "text": "As a rule of thumb, if the repair costs well under half of what replacing the iPad would, and the tablet still gets updates, repairing is the better call. TechBrotherz will give you an honest read on that at the Store rather than quoting a repair you should not buy.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "ipad",
    "featured": true,
    "order": 20,
    "plainAnswer": "Weigh four things: the repair price against a replacement, whether the iPad still gets iPadOS updates, whether the battery still holds a day of use, and whether anything else is failing. If the repair costs well under half of a replacement and the iPad still updates, repairing is usually better.",
    "published": true,
    "question": "What factors should I consider when deciding whether to repair or replace a broken iPad in Canada?"
  },
  {
    "_id": "faq.third-party-repair-and-warranty",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.third-party-repair-and-warranty-b0",
        "children": [
          {
            "_key": "faq.third-party-repair-and-warranty-s0",
            "marks": [],
            "text": "A third-party repair can affect the manufacturer warranty, particularly for the part that was replaced and for faults related to it. It does not automatically void everything, but it does complicate a later claim.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.third-party-repair-and-warranty-b1",
        "children": [
          {
            "_key": "faq.third-party-repair-and-warranty-s1",
            "marks": [],
            "text": "If your phone is still inside its manufacturer warranty and the fault is not accidental damage, going to the manufacturer first is usually the better route, and we will tell you so rather than take the work. Most people come to us because the warranty has expired, because the damage is accidental and therefore not covered anyway, or because they need the phone back today.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "warranty",
    "featured": false,
    "order": 180,
    "plainAnswer": "A third-party repair can affect the manufacturer warranty on the part that was replaced and on faults related to it. If your phone is still inside its manufacturer warranty and the fault is not accidental damage, it is usually worth going to the manufacturer first. We will tell you when that is the better route.",
    "published": true,
    "question": "Will a third-party repair void my phone's manufacturer warranty?"
  },
  {
    "_id": "faq.what-are-your-hours",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.what-are-your-hours-b0",
        "children": [
          {
            "_key": "faq.what-are-your-hours-s0",
            "marks": [],
            "text": "TechBrotherz is open Monday to Saturday from 10:00 AM to 7:00 PM, and Sunday from 11:00 AM to 5:00 PM.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.what-are-your-hours-b1",
        "children": [
          {
            "_key": "faq.what-are-your-hours-s1",
            "marks": [],
            "text": "No appointment is needed at any time. Come in during opening hours and we start on your device when you arrive. If you want to check a part is in stock before travelling, phone (403) 273-8324.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "location",
    "featured": true,
    "order": 170,
    "plainAnswer": "TechBrotherz is open Monday to Saturday from 10:00 AM to 7:00 PM, and Sunday from 11:00 AM to 5:00 PM. No appointment is needed. Come in during those hours and we start on your device when you arrive.",
    "published": true,
    "question": "What are your opening hours?"
  },
  {
    "_id": "faq.what-parts-do-you-use",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.what-parts-do-you-use-b0",
        "children": [
          {
            "_key": "faq.what-parts-do-you-use-s0",
            "marks": [],
            "text": "Part grade varies by model and by what is actually available for that model. Rather than make a blanket claim across every device we repair, we tell you at the Store exactly what is going into yours before the work starts.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.what-parts-do-you-use-b1",
        "children": [
          {
            "_key": "faq.what-parts-do-you-use-s1",
            "marks": [],
            "text": "Whatever the grade, every part we fit carries the same 60-day warranty on both the component and the workmanship. If a part fails inside that window, bring the device back and we replace it.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "parts",
    "featured": true,
    "order": 130,
    "plainAnswer": "Part grade varies by model and by what is available for it. Rather than make a blanket claim, we tell you at the Store exactly what is going into your device before the work starts, and every part we fit is covered by the same 60-day warranty.",
    "published": true,
    "question": "What quality of parts do you use?"
  },
  {
    "_id": "faq.what-warranty-comes-with-a-repair",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.what-warranty-comes-with-a-repair-b0",
        "children": [
          {
            "_key": "faq.what-warranty-comes-with-a-repair-s0",
            "marks": [],
            "text": "Every repair at TechBrotherz carries a 60-day warranty. It covers both the part we fit and the work we do, so if the part fails or the original fault returns within 60 days, bring the device back to 3317 17 Ave SE and we put it right.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.what-warranty-comes-with-a-repair-b1",
        "children": [
          {
            "_key": "faq.what-warranty-comes-with-a-repair-s1",
            "marks": [],
            "text": "The warranty does not cover new accidental damage. A fresh drop, a cracked screen from a new impact, or liquid getting into the device after the repair are not warranty claims, because they are new faults rather than a failure of our work.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "warranty",
    "featured": true,
    "order": 80,
    "plainAnswer": "Every repair at TechBrotherz carries a 60-day warranty covering both the part we fit and the workmanship. If the part fails or the fault returns within 60 days, bring the device back and we put it right. Accidental damage after the repair, such as a new drop or liquid, is not covered.",
    "published": true,
    "question": "What warranty comes with a repair?"
  },
  {
    "_id": "faq.where-are-you-and-is-there-parking",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.where-are-you-and-is-there-parking-b0",
        "children": [
          {
            "_key": "faq.where-are-you-and-is-there-parking-s0",
            "marks": [],
            "text": "TechBrotherz is at 3317 17 Ave SE in Calgary, on the stretch of 17 Avenue SE known as International Avenue, in the southeast, a few blocks west of Forest Lawn.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.where-are-you-and-is-there-parking-b1",
        "children": [
          {
            "_key": "faq.where-are-you-and-is-there-parking-s1",
            "marks": [],
            "text": "Parking is free in the plaza in front of the store. If you are coming by transit, the MAX Purple bus rapid transit line runs the full length of 17 Avenue SE between downtown Calgary and East Hills, with stops close to the store.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "location",
    "featured": true,
    "order": 160,
    "plainAnswer": "TechBrotherz is at 3317 17 Ave SE in Calgary, on the stretch of 17 Avenue SE known as International Avenue, a few blocks west of Forest Lawn. Parking is free in the plaza in front of the store, and the MAX Purple bus rapid transit line runs the length of the same street.",
    "published": true,
    "question": "Where is TechBrotherz and is there parking?"
  },
  {
    "_id": "faq.why-does-my-model-say-call-for-quote",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.why-does-my-model-say-call-for-quote-b0",
        "children": [
          {
            "_key": "faq.why-does-my-model-say-call-for-quote-s0",
            "marks": [],
            "text": "Call for quote means the part for that model is ordered in rather than held in stock, so the price moves with supply. We would rather show that honestly than publish a figure we might not be able to honour when you arrive.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.why-does-my-model-say-call-for-quote-b1",
        "children": [
          {
            "_key": "faq.why-does-my-model-say-call-for-quote-s1",
            "marks": [],
            "text": "Phone (403) 273-8324 with the exact model and we will give you a firm price and tell you how soon the part can be here. In most cases the repair still happens the same day or the next.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "pricing",
    "featured": true,
    "order": 100,
    "plainAnswer": "Call for quote means the part is ordered in rather than held in stock, so the price depends on the day's supply. We would rather show that honestly than publish a number we might not be able to honour. Phone (403) 273-8324 with your model and we will give you an exact figure.",
    "published": true,
    "question": "Why do some models say Call for quote instead of showing a price?"
  },
  {
    "_id": "faq.will-i-lose-my-data",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.will-i-lose-my-data-b0",
        "children": [
          {
            "_key": "faq.will-i-lose-my-data-s0",
            "marks": [],
            "text": "A screen, battery, charging port, button or camera repair does not touch the storage chip, so your photos, messages, contacts and apps stay exactly where they are.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.will-i-lose-my-data-b1",
        "children": [
          {
            "_key": "faq.will-i-lose-my-data-s1",
            "marks": [],
            "text": "We still recommend backing up before you bring any device in. No repair is completely without risk, a device that arrives with a hidden fault can behave unpredictably, and a backup costs you nothing. On an iPhone use iCloud or a computer, and on Android use Google One or your phone maker's backup tool.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "data",
    "featured": true,
    "order": 110,
    "plainAnswer": "A screen, battery, charging port or camera repair does not touch your storage, so your photos, messages and apps stay exactly as they are. We still recommend backing up before any repair, because no repair is completely risk free and a backup costs you nothing.",
    "published": true,
    "question": "Will I lose my photos and data during a repair?"
  },
  {
    "_id": "faq.worth-repairing-older-ipad",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "answer": [
      {
        "_key": "faq.worth-repairing-older-ipad-b0",
        "children": [
          {
            "_key": "faq.worth-repairing-older-ipad-s0",
            "marks": [],
            "text": "An older iPad is worth repairing when three things are true: the glass is the only fault, the battery still gets through the day, and the tablet still receives iPadOS updates. At TechBrotherz, glass replacement on an iPad 2, 3 or 4 is the smallest tablet repair we quote, a job small enough to justify for a tablet used for video, reading, recipes or as a second screen for a child.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.worth-repairing-older-ipad-b1",
        "children": [
          {
            "_key": "faq.worth-repairing-older-ipad-s1",
            "marks": [],
            "text": "Replacing makes more sense when the iPad has stopped receiving updates, when the battery no longer lasts, or when the repair would cost a large fraction of a replacement. Apps drop support for old iPadOS versions over time, so an iPad that no longer updates will slowly stop running the things you want.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      },
      {
        "_key": "faq.worth-repairing-older-ipad-b2",
        "children": [
          {
            "_key": "faq.worth-repairing-older-ipad-s2",
            "marks": [],
            "text": "Bring the iPad to 3317 17 Ave SE in Calgary and we will check the battery and the software version with you before quoting, so you are deciding with real information rather than a guess.",
            "_type": "span"
          }
        ],
        "markDefs": [],
        "style": "normal",
        "_type": "block"
      }
    ],
    "category": "ipad",
    "featured": true,
    "order": 40,
    "plainAnswer": "An older iPad is worth repairing when the glass is the only fault, the battery still lasts, and the tablet still gets iPadOS updates. At TechBrotherz, glass replacement on an iPad 2, 3 or 4 is the smallest tablet repair we quote, a job small enough to be worth it for a tablet used for video, reading or as a kitchen screen.",
    "published": true,
    "question": "Is it worth repairing an older iPad model or should I just replace it with a newer one?"
  }
] as unknown as FaqDoc[];
