/**
 * GENERATED by scripts/export-content.ts from the Sanity dataset.
 *
 * Fixed-price services: virus removal, Windows installation, tune-ups.
 *
 * This file is now the source of truth. Edit it directly: there is no dataset
 * behind it and no import step to re-run.
 */

import type { FlatServiceDoc } from "./types";

export const FLAT_SERVICE_DOCS: FlatServiceDoc[] = [
  {
    "_id": "flatService.dc-charging-port-replacement",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "category": "computer",
    "description": "A worn or broken laptop charging socket replaced for $109.99, including stripping the machine down and testing charging under load before reassembly.",
    "name": "DC / charging port replacement",
    "needsVerification": false,
    "noIndex": false,
    "order": 90,
    "price": 109.99,
    "priceFrom": false,
    "published": true,
    "quoteOnly": false,
    "slug": {
      "current": "dc-charging-port-replacement"
    },
    "turnaroundMinutes": 90
  },
  {
    "_id": "flatService.diagnostics",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "category": "computer",
    "description": "We test the machine and tell you exactly what has failed and what it costs to fix, for $24.99, before you commit to any repair.",
    "includes": [
      "Full hardware test covering drive, memory and power",
      "A written list of what has failed",
      "A firm price for the repair before any work starts"
    ],
    "name": "Diagnostics",
    "needsVerification": false,
    "noIndex": false,
    "order": 10,
    "price": 24.99,
    "priceFrom": false,
    "published": true,
    "quoteOnly": false,
    "slug": {
      "current": "diagnostics"
    },
    "turnaroundMinutes": 60
  },
  {
    "_id": "flatService.hardware-installation",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "category": "computer",
    "description": "Any single component fitted for $24.99, covering the labour to install memory, a drive or a card. The part itself is extra.",
    "name": "Hardware installation, each",
    "needsVerification": false,
    "noIndex": false,
    "order": 60,
    "price": 24.99,
    "priceFrom": false,
    "published": true,
    "quoteOnly": false,
    "slug": {
      "current": "hardware-installation"
    },
    "turnaroundMinutes": 45
  },
  {
    "_id": "flatService.laptop-keyboard-replacement",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "category": "computer",
    "description": "A laptop keyboard replaced for between $69.99 and $149.99. The range is real: on some laptops the keyboard is a separate part, and on others it is riveted into the whole top case, which costs more.",
    "name": "Laptop keyboard replacement",
    "needsVerification": false,
    "noIndex": false,
    "order": 100,
    "price": 69.99,
    "priceFrom": false,
    "priceTo": 149.99,
    "published": true,
    "quoteOnly": false,
    "slug": {
      "current": "laptop-keyboard-replacement"
    },
    "turnaroundMinutes": 90
  },
  {
    "_id": "flatService.laptop-screen-replacement",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "category": "computer",
    "description": "A cracked or failed laptop screen replaced from $120, including the panel and the labour. The final price depends on the size and resolution of the panel your model takes.",
    "includes": [
      "New display panel fitted",
      "Hinges and cables checked while the machine is open",
      "60-day warranty on the panel and the work"
    ],
    "name": "Laptop screen replacement",
    "needsVerification": false,
    "noIndex": false,
    "order": 80,
    "price": 120,
    "priceFrom": true,
    "published": true,
    "quoteOnly": false,
    "slug": {
      "current": "laptop-screen-replacement"
    },
    "turnaroundMinutes": 90
  },
  {
    "_id": "flatService.password-reset",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "category": "software",
    "description": "A locked Windows account reset for $49.99, so you get back into the machine without losing the files on it.",
    "includes": [
      "Windows local or Microsoft account access restored",
      "Files on the machine left in place"
    ],
    "name": "Password reset",
    "needsVerification": true,
    "noIndex": false,
    "order": 70,
    "price": 49.99,
    "priceFrom": false,
    "published": true,
    "quoteOnly": false,
    "slug": {
      "current": "password-reset"
    },
    "turnaroundMinutes": 45
  },
  {
    "_id": "flatService.program-installation",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "category": "software",
    "description": "Any single program installed and set up for $24.99, including licensing and first-run configuration.",
    "name": "Program installation, each",
    "needsVerification": false,
    "noIndex": false,
    "order": 50,
    "price": 24.99,
    "priceFrom": false,
    "published": true,
    "quoteOnly": false,
    "slug": {
      "current": "program-installation"
    },
    "turnaroundMinutes": 30
  },
  {
    "_id": "flatService.tune-up",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "category": "computer",
    "description": "A full clean-up and tune-up for $79.99, covering both the software slowing the machine down and the dust cooking it from the inside.",
    "includes": [
      "Startup programs and background tasks cleared out",
      "Dust removed from fans and heatsinks",
      "Drive health checked and reported",
      "Windows and driver updates applied"
    ],
    "name": "Desktop clean-up and tune-up",
    "needsVerification": false,
    "noIndex": false,
    "order": 40,
    "price": 79.99,
    "priceFrom": false,
    "published": true,
    "quoteOnly": false,
    "slug": {
      "current": "tune-up"
    },
    "turnaroundMinutes": 180
  },
  {
    "_id": "flatService.virus-removal",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "category": "software",
    "description": "Malware, adware and browser hijackers removed for $34.99, with security software left in place so the machine does not pick the same thing up again.",
    "includes": [
      "Full scan and removal of malware and adware",
      "Browser hijackers and unwanted toolbars removed",
      "Security software installed and set to update itself"
    ],
    "name": "Virus removal",
    "needsVerification": false,
    "noIndex": false,
    "order": 30,
    "price": 34.99,
    "priceFrom": false,
    "published": true,
    "quoteOnly": false,
    "slug": {
      "current": "virus-removal"
    },
    "turnaroundMinutes": 120
  },
  {
    "_id": "flatService.windows-installation",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "category": "software",
    "description": "A clean Windows installation for $44.99, including Microsoft Office and security software, with all drivers set up so the machine works out of the box.",
    "includes": [
      "Clean Windows installation",
      "Microsoft Office installed",
      "Security software installed",
      "All hardware drivers installed and tested"
    ],
    "name": "Windows installation",
    "needsVerification": false,
    "noIndex": false,
    "order": 20,
    "price": 44.99,
    "priceFrom": false,
    "published": true,
    "quoteOnly": false,
    "slug": {
      "current": "windows-installation"
    },
    "turnaroundMinutes": 120
  }
] as unknown as FlatServiceDoc[];
