/**
 * GENERATED by scripts/export-locations.ts from the Sanity dataset.
 *
 * The eleven places the site describes. Whole documents, not a projection: the
 * accessors in lib/data/locations.ts need `published` to reproduce the LIVE
 * filter and `distanceKm` to reproduce the nearest-first ordering, and the
 * Phase 6.9 export dropped both.
 *
 * This file is now the source of truth. Edit it directly.
 */

import type { LocationDoc } from "./types";

export const LOCATION_DOCS: LocationDoc[] = [
  {
    "_id": "location.airdrie",
    "_updatedAt": "2026-07-30T17:00:10Z",
    "city": "Airdrie",
    "isPrimary": false,
    "kind": "city",
    "landmarks": [
      "Queen Elizabeth II Highway",
      "Deerfoot Trail"
    ],
    "noIndex": false,
    "order": 110,
    "province": "Alberta",
    "published": false,
    "routeDescription": "TODO(client): Airdrie sits north of Calgary. Confirm the route customers take, the real driving distance and the typical drive time before this page is published.",
    "slug": {
      "_type": "slug",
      "current": "airdrie"
    }
  },
  {
    "_id": "location.albert-park",
    "_updatedAt": "2026-07-30T17:00:10Z",
    "city": "Albert Park",
    "isPrimary": false,
    "kind": "neighbourhood",
    "landmarks": [
      "17 Avenue SE",
      "Radisson Heights"
    ],
    "noIndex": false,
    "order": 40,
    "parent": {
      "_ref": "location.calgary",
      "_type": "reference"
    },
    "province": "Alberta",
    "published": false,
    "routeDescription": "TODO(client): Albert Park and Radisson Heights sit immediately west of Forest Lawn along 17 Avenue SE. Confirm the drive time and any landmarks locals use before this page is published.",
    "slug": {
      "_type": "slug",
      "current": "albert-park"
    }
  },
  {
    "_id": "location.calgary",
    "_updatedAt": "2026-07-30T17:00:10Z",
    "city": "Calgary",
    "commonRepairs": [
      "iPhone and Samsung screen replacement",
      "Phone battery replacement",
      "Charging port repair",
      "Laptop screen replacement and Windows installation",
      "Carrier unlocking"
    ],
    "distanceKm": 0,
    "driveTimeMinutes": 0,
    "isPrimary": true,
    "kind": "city",
    "landmarks": [
      "International Avenue, the business district along 17 Avenue SE",
      "The MAX Purple bus rapid transit line, which runs the length of 17 Avenue SE",
      "Elliston Park, east along 17 Avenue SE"
    ],
    "neighbourhoods": [
      "Forest Lawn",
      "Albert Park",
      "Radisson Heights",
      "Dover",
      "Southview",
      "Erin Woods",
      "Penbrooke Meadows",
      "Inglewood",
      "Ogden",
      "Marlborough",
      "Downtown Calgary"
    ],
    "noIndex": false,
    "order": 10,
    "province": "Alberta",
    "published": true,
    "routeDescription": "TechBrotherz is at 3317 17 Ave SE, on International Avenue in southeast Calgary. 17 Avenue SE runs east to west across the whole southeast, so most of the city reaches the store on one road without turning off. Parking is free in the plaza in front of the store.",
    "seoDescription": "Walk-in phone, tablet and computer repair at 3317 17 Ave SE in Calgary. Most repairs about 30 minutes, parts and labour included, 60-day warranty.",
    "seoTitle": "Phone and Computer Repair in Calgary",
    "slug": {
      "_type": "slug",
      "current": "calgary"
    },
    "transitDescription": "The MAX Purple bus rapid transit line runs the full length of 17 Avenue SE, connecting downtown Calgary to East Hills, with stops along International Avenue close to the store."
  },
  {
    "_id": "location.chestermere",
    "_updatedAt": "2026-07-30T17:00:10Z",
    "city": "Chestermere",
    "isPrimary": false,
    "kind": "city",
    "landmarks": [
      "Chestermere Lake",
      "Trans-Canada Highway"
    ],
    "noIndex": false,
    "order": 100,
    "province": "Alberta",
    "published": false,
    "routeDescription": "TODO(client): Chestermere sits east of Calgary. Confirm the route customers take, the real driving distance and the typical drive time before this page is published.",
    "slug": {
      "_type": "slug",
      "current": "chestermere"
    }
  },
  {
    "_id": "location.dover",
    "_updatedAt": "2026-07-30T17:00:10Z",
    "city": "Dover",
    "isPrimary": false,
    "kind": "neighbourhood",
    "landmarks": [
      "36 Street SE",
      "17 Avenue SE"
    ],
    "noIndex": false,
    "order": 50,
    "parent": {
      "_ref": "location.calgary",
      "_type": "reference"
    },
    "province": "Alberta",
    "published": false,
    "routeDescription": "TODO(client): Dover lies south of 17 Avenue SE. Confirm the route, the drive time and the landmarks locals use before this page is published.",
    "slug": {
      "_type": "slug",
      "current": "dover"
    }
  },
  {
    "_id": "location.downtown",
    "_updatedAt": "2026-07-30T17:00:10Z",
    "city": "Downtown Calgary",
    "isPrimary": false,
    "kind": "neighbourhood",
    "landmarks": [
      "Downtown core",
      "Memorial Drive",
      "17 Avenue SE"
    ],
    "noIndex": false,
    "order": 90,
    "parent": {
      "_ref": "location.calgary",
      "_type": "reference"
    },
    "province": "Alberta",
    "published": false,
    "routeDescription": "TODO(client): downtown customers usually reach the store by heading east on Memorial Drive or 17 Avenue SE. Confirm the route and drive time before this page is published.",
    "slug": {
      "_type": "slug",
      "current": "downtown"
    }
  },
  {
    "_id": "location.forest-lawn",
    "_updatedAt": "2026-07-30T17:00:10Z",
    "city": "Forest Lawn",
    "commonRepairs": [
      "iPhone and Samsung screen replacement",
      "Phone battery replacement",
      "Carrier unlocking",
      "Charging port repair"
    ],
    "distanceKm": 0.5,
    "driveTimeMinutes": 2,
    "isPrimary": false,
    "kind": "neighbourhood",
    "landmarks": [
      "International Avenue, which is the name 17 Avenue SE carries through Forest Lawn",
      "Forest Lawn High School",
      "Elliston Park, east along 17 Avenue SE"
    ],
    "noIndex": false,
    "order": 20,
    "parent": {
      "_ref": "location.calgary",
      "_type": "reference"
    },
    "province": "Alberta",
    "published": true,
    "routeDescription": "TechBrotherz is inside Forest Lawn. The store sits at 3317 17 Ave SE, on the stretch of 17 Avenue SE known as International Avenue, so most of Forest Lawn is a short walk or a two minute drive away. Parking is free in the plaza in front of the store.",
    "seoDescription": "TechBrotherz is on International Avenue in Forest Lawn at 3317 17 Ave SE. Walk in, no appointment, most repairs about 30 minutes.",
    "seoTitle": "Phone Repair in Forest Lawn, Calgary",
    "slug": {
      "_type": "slug",
      "current": "forest-lawn"
    },
    "transitDescription": "MAX Purple stops along International Avenue put the store within a short walk of most of Forest Lawn."
  },
  {
    "_id": "location.inglewood",
    "_updatedAt": "2026-07-30T17:00:10Z",
    "city": "Inglewood",
    "isPrimary": false,
    "kind": "neighbourhood",
    "landmarks": [
      "9 Avenue SE",
      "Blackfoot Trail"
    ],
    "noIndex": false,
    "order": 60,
    "parent": {
      "_ref": "location.calgary",
      "_type": "reference"
    },
    "province": "Alberta",
    "published": false,
    "routeDescription": "TODO(client): Inglewood sits west of the store along 9 Avenue SE. Confirm the route, the drive time and the landmarks locals use before this page is published.",
    "slug": {
      "_type": "slug",
      "current": "inglewood"
    }
  },
  {
    "_id": "location.marlborough",
    "_updatedAt": "2026-07-30T17:00:10Z",
    "city": "Marlborough",
    "isPrimary": false,
    "kind": "neighbourhood",
    "landmarks": [
      "Marlborough Mall",
      "Memorial Drive",
      "36 Street NE"
    ],
    "noIndex": false,
    "order": 70,
    "parent": {
      "_ref": "location.calgary",
      "_type": "reference"
    },
    "province": "Alberta",
    "published": false,
    "routeDescription": "TODO(client): Marlborough sits north of the store across Memorial Drive. Confirm the route and drive time before this page is published.",
    "slug": {
      "_type": "slug",
      "current": "marlborough"
    }
  },
  {
    "_id": "location.ogden",
    "_updatedAt": "2026-07-30T17:00:10Z",
    "city": "Ogden",
    "isPrimary": false,
    "kind": "neighbourhood",
    "landmarks": [
      "Ogden Road SE",
      "Glenmore Trail"
    ],
    "noIndex": false,
    "order": 80,
    "parent": {
      "_ref": "location.calgary",
      "_type": "reference"
    },
    "province": "Alberta",
    "published": false,
    "routeDescription": "TODO(client): Ogden sits southwest of the store. Confirm the route and drive time before this page is published.",
    "slug": {
      "_type": "slug",
      "current": "ogden"
    }
  },
  {
    "_id": "location.southeast-calgary",
    "_updatedAt": "2026-07-30T17:00:10Z",
    "city": "Southeast Calgary",
    "isPrimary": false,
    "kind": "neighbourhood",
    "landmarks": [
      "17 Avenue SE",
      "Deerfoot Trail",
      "Glenmore Trail"
    ],
    "noIndex": false,
    "order": 30,
    "parent": {
      "_ref": "location.calgary",
      "_type": "reference"
    },
    "province": "Alberta",
    "published": false,
    "routeDescription": "TODO(client): confirm the routes and typical drive times most southeast customers actually take, before this page is published.",
    "seoDescription": "TechBrotherz repairs phones, tablets and computers in southeast Calgary at 3317 17 Ave SE. Walk in, no appointment needed.",
    "seoTitle": "Phone Repair in Southeast Calgary",
    "slug": {
      "_type": "slug",
      "current": "southeast-calgary"
    }
  }
] as unknown as LocationDoc[];
