/**
 * GENERATED by scripts/export-content.ts from the Sanity dataset.
 *
 * The business facts. The single source of truth for NAP, hours, warranty and
 * the announcement bar. CLAUDE.md Section 2 is the human-readable copy of this.
 *
 * This file is now the source of truth. Edit it directly: there is no dataset
 * behind it and no import step to re-run.
 */

import type { SiteSettingsDoc } from "./types";

export const SITE_SETTINGS: SiteSettingsDoc = {
  "_id": "siteSettings",
  "_updatedAt": "2026-07-31T13:46:14Z",
  "announcementBar": {
    "active": false,
    "text": ""
  },
  "appointmentPolicy": "No appointment needed, walk-ins welcome",
  "brandName": "TechBrotherz",
  "city": "Calgary",
  "country": "Canada",
  "geo": {
    "lat": 51.0366821,
    "lng": -113.9869842
  },
  "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=3317+17+Ave+SE+Calgary+Alberta",
  "googleReviewsUrl": "https://www.google.com/maps/place/TechBrotherz/@51.0366821,-113.9869842,17z/data=!3m1!5s0x53717ae7a5d4f8d7:0xb018a331a11900ca!4m8!3m7!1s0x53717ae777fa04f7:0xe21ea3f908974600!8m2!3d51.0366821!4d-113.9869842!9m1!1b1!16s%2Fg%2F1ptx_hp3y!18m1!1e1",
  "socialLinks": [
    {
      "platform": "TikTok",
      "url": "https://www.tiktok.com/@techbrotherzyyc"
    },
    {
      "platform": "Instagram",
      "url": "https://www.instagram.com/techbrotherz_yyc"
    },
    {
      "platform": "Facebook",
      "url": "https://www.facebook.com/Techbrotherzcalgary/"
    }
  ],
  "hours": [
    {
      "_key": "mon",
      "close": "19:00",
      "closed": false,
      "day": "Monday",
      "open": "10:00"
    },
    {
      "_key": "tue",
      "close": "19:00",
      "closed": false,
      "day": "Tuesday",
      "open": "10:00"
    },
    {
      "_key": "wed",
      "close": "19:00",
      "closed": false,
      "day": "Wednesday",
      "open": "10:00"
    },
    {
      "_key": "thu",
      "close": "19:00",
      "closed": false,
      "day": "Thursday",
      "open": "10:00"
    },
    {
      "_key": "fri",
      "close": "19:00",
      "closed": false,
      "day": "Friday",
      "open": "10:00"
    },
    {
      "_key": "sat",
      "close": "19:00",
      "closed": false,
      "day": "Saturday",
      "open": "10:00"
    },
    {
      "_key": "sun",
      "close": "17:00",
      "closed": false,
      "day": "Sunday",
      "open": "11:00"
    }
  ],
  "legalName": "TechBrotherz",
  "phone": "(403) 273-8324",
  "phoneRaw": "+14032738324",
  "priceDisclaimer": "All prices include the part and labour, and every repair is covered by a 60-day warranty.",
  "region": "Alberta",
  "regionCode": "AB",
  /*
   * The store's real Google rating, read from the client's own listing (the
   * one whose URL they supplied) as displayed on Google's own embed card,
   * verified 2026-08-14 by loading the embed and reading the card:
   * "TechBrotherz ... 4.8 ★ (732)". Not invented, not estimated, and dated so
   * staleness is visible. A snapshot rather than a live feed: the Places API
   * key (question 8) upgrades this to auto-refreshing data. Re-verify and
   * update lastVerified whenever these numbers are touched.
   */
  "reviewSummary": {
    "enabled": true,
    "ratingValue": 4.8,
    "reviewCount": 732,
    "source": "Google",
    "sourceUrl": "https://www.google.com/maps/place/TechBrotherz/@51.0366821,-113.9869842,17z/data=!3m1!5s0x53717ae7a5d4f8d7:0xb018a331a11900ca!4m8!3m7!1s0x53717ae777fa04f7:0xe21ea3f908974600!8m2!3d51.0366821!4d-113.9869842!9m1!1b1!16s%2Fg%2F1ptx_hp3y!18m1!1e1",
    "lastVerified": "2026-08-14"
  },
  "street": "3317 17 Ave SE",
  "tagline": "Phone and computer repairs, done while you wait",
  "typicalWaitMinutes": 30,
  "warrantyDays": 60
} as unknown as SiteSettingsDoc;
