/**
 * GENERATED by scripts/export-content.ts from the Sanity dataset.
 *
 * The business facts. The single source of truth for NAP, hours, warranty and
 * the announcement bar. CLAUDE.md Section 2 is the human-readable copy of this.
 *
 * This file is now the source of truth. Edit it directly: there is no dataset
 * behind it and no import step to re-run.
 */

import type { SiteSettingsDoc } from "./types";

export const SITE_SETTINGS: SiteSettingsDoc = {
  "_id": "siteSettings",
  "_updatedAt": "2026-07-31T13:46:14Z",
  "announcementBar": {
    "active": false,
    "text": ""
  },
  "appointmentPolicy": "No appointment needed, walk-ins welcome",
  "brandName": "TechBrotherz",
  "city": "Calgary",
  "country": "Canada",
  "googleMapsUrl": "https://www.google.com/maps/search/?api=1&query=3317+17+Ave+SE+Calgary+Alberta",
  "hours": [
    {
      "_key": "mon",
      "close": "19:00",
      "closed": false,
      "day": "Monday",
      "open": "10:00"
    },
    {
      "_key": "tue",
      "close": "19:00",
      "closed": false,
      "day": "Tuesday",
      "open": "10:00"
    },
    {
      "_key": "wed",
      "close": "19:00",
      "closed": false,
      "day": "Wednesday",
      "open": "10:00"
    },
    {
      "_key": "thu",
      "close": "19:00",
      "closed": false,
      "day": "Thursday",
      "open": "10:00"
    },
    {
      "_key": "fri",
      "close": "19:00",
      "closed": false,
      "day": "Friday",
      "open": "10:00"
    },
    {
      "_key": "sat",
      "close": "19:00",
      "closed": false,
      "day": "Saturday",
      "open": "10:00"
    },
    {
      "_key": "sun",
      "close": "17:00",
      "closed": false,
      "day": "Sunday",
      "open": "11:00"
    }
  ],
  "legalName": "TechBrotherz",
  "phone": "(403) 273-8324",
  "phoneRaw": "+14032738324",
  "priceDisclaimer": "All prices include the part and labour, and every repair is covered by a 60-day warranty.",
  "region": "Alberta",
  "regionCode": "AB",
  "street": "3317 17 Ave SE",
  "tagline": "Phone and computer repairs, done while you wait",
  "typicalWaitMinutes": 30,
  "warrantyDays": 60
} as unknown as SiteSettingsDoc;
