/**
 * GENERATED by scripts/export-content.ts from the Sanity dataset.
 *
 * Real reviews only, and only where `verified` is true and a sourceUrl exists.
 * Dormant until the client supplies them. Never fabricate an entry here.
 *
 * This file is now the source of truth. Edit it directly: there is no dataset
 * behind it and no import step to re-run.
 */

import type { TestimonialDoc } from "./types";

export const TESTIMONIAL_DOCS: TestimonialDoc[] = [] as unknown as TestimonialDoc[];
