/**
 * GENERATED by scripts/export-content.ts from the Sanity dataset.
 *
 * Carrier unlocking, by carrier and device type.
 *
 * This file is now the source of truth. Edit it directly: there is no dataset
 * behind it and no import step to re-run.
 */

import type { UnlockingDoc } from "./types";

export const UNLOCKING_DOCS: UnlockingDoc[] = [
  {
    "_id": "unlocking.any-canadian-carrier",
    "_updatedAt": "2026-07-30T17:00:06Z",
    "carrier": "Any Canadian carrier",
    "deviceType": "phone",
    "notes": "Covers phones locked to any Canadian carrier, including Rogers, Bell, Telus, Fido, Koodo, Virgin, Freedom, Chatr and Public Mobile. Since December 2017 the CRTC Wireless Code has required Canadian carriers to unlock phones free on request, so ask your carrier first. Bring the phone to us when the carrier will not do it, when the phone came from someone else, or when you want it done while you wait. Unlocking does not erase your data and does not void the manufacturer warranty. A phone reported lost or stolen is on the national blacklist and cannot be unlocked by anyone, including us.",
    "order": 10,
    "price": 35,
    "published": true,
    "turnaround": "Usually the same day"
  }
] as unknown as UnlockingDoc[];
