/**
 * Writes content/image-manifest.md from lib/content/images.ts.
 *
 * Generated rather than hand-maintained, so the manifest cannot drift from
 * what the site actually renders. Replacing the demo set with the client's own
 * photography is then a mechanical job: swap the file, change the alt text and
 * the credit in one place, rerun this.
 *
 *   pnpm exec tsx scripts/build-image-manifest.ts
 */

import { existsSync, statSync, writeFileSync } from "node:fs";
import path from "node:path";

import { IMAGE_EDITS, IMAGES, ILLUSTRATED_SLOTS } from "../lib/content/images";

function sizeOf(file: string): string {
  const onDisk = path.join(process.cwd(), "public", file.replace(/^\//, ""));
  if (!existsSync(onDisk)) return "missing";
  return `${(statSync(onDisk).size / 1024).toFixed(0)} KB`;
}

function main() {
  const rows = Object.values(IMAGES);

  const lines: string[] = [
    "# Image manifest",
    "",
    "> Generated by `pnpm exec tsx scripts/build-image-manifest.ts` from",
    "> `lib/content/images.ts`. Do not edit by hand.",
    "",
    "Every image here is a **demo placeholder** for photography the client has not",
    "taken yet. Two rules govern the set:",
    "",
    "1. **Stock may show the work, never the business.** No stock image is presented",
    "   as TechBrotherz, its premises, its technicians or its customers. Alt text",
    "   describes what the photograph shows, never who it is.",
    "2. **Nothing is load-bearing.** Delete `public/demo/` and every page still",
    "   builds and renders, without pictures.",
    "",
    "Location pages, `/about` and `/contact` carry no photography by design. A map",
    "and an address are the honest content for a place.",
    "",
    "## Sourcing",
    "",
    "`source.unsplash.com` was deprecated in 2021 and shut down in 2024, so any code",
    "or tutorial using it fails. Originals were downloaded by hand from unsplash.com",
    "and are committed under `public/demo/_source/`. The running site never touches",
    "an Unsplash URL. The Unsplash License permits free commercial use without",
    "attribution; the credits below are recorded because it is the decent thing and",
    "because it makes the set auditable, not because it is required.",
    "",
    "Processing is `pnpm exec tsx scripts/process-images.ts`: crop to ratio, cap the",
    "long edge at 1600px, JPEG quality 74, plus a 16px base64 LQIP for the blur",
    "placeholder so this pass cannot cost us the 0.000 CLS record.",
    "",
    "## Filled slots",
    "",
    "| Slot | File | Ratio | Size | Photographer | Source | Alt text | Edits |",
    "|---|---|---|---|---|---|---|---|",
  ];

  for (const image of rows) {
    lines.push(
      `| \`${image.slot}\` | \`${image.file}\` | ${image.ratio} | ${sizeOf(image.file)} | ${image.photographer} | [Unsplash](${image.sourceUrl}) | ${image.alt} | ${IMAGE_EDITS[image.slot] ?? "Crop and resize only"} |`,
    );
  }

  lines.push(
    "",
    "## Slots that use an illustration",
    "",
    "The Phase 6.5 constraint, no visible manufacturer marks at all, was replaced in",
    "Phase 6.5b by the narrower rule that actually matters: a manufacturer logo may",
    "not be used **as a mark**, may not be the dominant or isolated element of an",
    "image, and nothing may imply authorised status. Incidental marks inside a",
    "workshop photograph are ordinary and expected. That change filled every header",
    "slot with real photography.",
    "",
    "What remains illustrated is deliberate, not a gap.",
    "",
    "| Slot | Why it is illustrated |",
    "|---|---|",
  );

  for (const slot of ILLUSTRATED_SLOTS) {
    lines.push(`| ${slot.slot} | ${slot.reason} |`);
  }

  lines.push(
    "",
    "## Replacing the demo set",
    "",
    "1. Photograph the shop, the bench, the storefront and the technicians. Google",
    "   Business Profile needs those photographs anyway, so it is work that has to",
    "   happen regardless of this site.",
    "2. Drop the originals into `public/demo/_source/` using the same slot names.",
    "3. Update the alt text and credit in `lib/content/images.ts`.",
    "4. Run `pnpm exec tsx scripts/process-images.ts` then this script.",
    "",
    "Real photographs of the actual shop can say what stock never can, and at that",
    "point the alt-text rule relaxes: once the picture genuinely is the TechBrotherz",
    "counter, it can say so.",
    "",
  );

  writeFileSync("content/image-manifest.md", lines.join("\n"), "utf8");
  console.log(
    `content/image-manifest.md written: ${rows.length} filled, ${ILLUSTRATED_SLOTS.length} empty slot groups`,
  );
}

main();
