/**
 * Writes content/models/<slug>.ts from the live dataset, plus an index.
 *
 * Read-only against Sanity: this is the "move" half of Phase 6.9, and it can
 * run and be reviewed long before anything is deleted. A model only gets a
 * file if it has copy worth moving, so the models that come out with nothing
 * are exactly the ones that will render the lean template.
 *
 *   pnpm exec tsx --env-file=.env.local scripts/extract-model-content.ts
 */

import { mkdirSync, writeFileSync } from "node:fs";
import path from "node:path";

import { createReadClient } from "../sanity/lib/write-client";

const OUT = "content/models";

interface Row {
  name: string | null;
  slug: string | null;
  intro: unknown;
  commonIssues: string[] | null;
  verdict: unknown;
  repairNotes: unknown;
  lastSupportedOs: string | null;
  stillReceivesUpdates: boolean | null;
  pricedCount: number;
}

const client = createReadClient(process.env.NEXT_PUBLIC_SANITY_DATASET ?? "production");

/** A model has copy worth moving when it has an intro or real issue list. */
function hasCopy(row: Row): boolean {
  return Boolean(row.intro) || (row.commonIssues?.length ?? 0) >= 3 || Boolean(row.verdict);
}

function fileFor(row: Row): string {
  const body = {
    slug: row.slug,
    name: row.name,
    intro: row.intro ?? null,
    commonIssues: row.commonIssues ?? [],
    verdict: row.verdict ?? null,
    repairNotes: row.repairNotes ?? null,
    lastSupportedOs: row.lastSupportedOs ?? null,
    stillReceivesUpdates: row.stillReceivesUpdates ?? null,
  };

  return `/**
 * GENERATED from the Sanity dataset in the Phase 6.9 move.
 *
 * Copy lives in the repo now, not the CMS, so the similarity detector and the
 * word-count check run over it in a pull request. Edit it here.
 */

import type { ModelContent } from "@/lib/content/model-content";

const content: ModelContent = ${JSON.stringify(body, null, 2)} as ModelContent;

export default content;
`;
}

async function main() {
  const rows = await client.fetch<Row[]>(`
    *[_type == "deviceModel" && !(_id in path("drafts.**"))]{
      name, "slug": slug.current, intro, commonIssues, verdict, repairNotes,
      lastSupportedOs, stillReceivesUpdates,
      "pricedCount": count(*[_type == "priceEntry" && model._ref == ^._id && defined(price)])
    } | order(slug asc)
  `);

  mkdirSync(OUT, { recursive: true });

  const written: string[] = [];
  const lean: string[] = [];
  const unbuildable: string[] = [];

  for (const row of rows) {
    if (!row.slug) continue;

    if (hasCopy(row)) {
      writeFileSync(path.join(OUT, `${row.slug}.ts`), fileFor(row), "utf8");
      written.push(row.slug);
    } else if (row.pricedCount > 0) {
      lean.push(row.slug);
    } else {
      unbuildable.push(row.slug);
    }
  }

  /* A static import map, so a missing file is a compile error not a runtime one. */
  const index = `/**
 * GENERATED by scripts/extract-model-content.ts. Do not edit.
 *
 * A static map rather than a dynamic import, so a model referenced without a
 * file is a compile error rather than a blank page at request time.
 */

import type { ModelContent } from "@/lib/content/model-content";

${written.map((slug, index_) => `import m${index_} from "@/content/models/${slug}";`).join("\n")}

export const MODEL_CONTENT: Record<string, ModelContent> = {
${written.map((slug, index_) => `  ${JSON.stringify(slug)}: m${index_},`).join("\n")}
};
`;

  writeFileSync(path.join(OUT, "index.ts"), index, "utf8");

  console.log(`\n  models read        : ${rows.length}`);
  console.log(`  full, file written : ${written.length}`);
  console.log(`  lean, prices only  : ${lean.length}`);
  console.log(`  unbuildable        : ${unbuildable.length}`);
  if (lean.length > 0)
    console.log(`\n  lean: ${lean.slice(0, 12).join(", ")}${lean.length > 12 ? ", ..." : ""}`);
  if (unbuildable.length > 0) {
    console.log(
      `\n  unbuildable: ${unbuildable.slice(0, 12).join(", ")}${unbuildable.length > 12 ? ", ..." : ""}`,
    );
  }
}

main().catch((error) => {
  console.error("extract-model-content failed:", error);
  process.exit(1);
});

export {};
