/**
 * Emits lib/content/brands.ts and lib/content/repair-types.ts from the live
 * dataset.
 *
 * Generated rather than hand-copied, because Phase 6.9 is a move and not a
 * rewrite: the rendered pages must be byte-identical afterwards, and
 * retyping nine intros and sixteen descriptions by hand is exactly how a
 * "move" quietly becomes an edit.
 *
 *   pnpm exec tsx --env-file=.env.local scripts/generate-constants.ts
 */

import { readFileSync, writeFileSync } from "node:fs";

interface Brand {
  name: string;
  slug: string;
  type: string;
  order: number;
  active: boolean;
  intro?: unknown;
  seoTitle?: string;
  seoDescription?: string;
}

interface RepairType {
  name: string;
  slug: string;
  icon?: string;
  shortDescription?: string;
  longDescription?: unknown;
  estimatedMinutes?: number;
  appliesTo?: string[];
  symptoms?: string[];
  order?: number;
}

interface PriceGroup {
  name: string;
  note?: string;
  models: string[];
}

const dump = JSON.parse(readFileSync("snapshots/sanity-dump.json", "utf8")) as {
  brands: Brand[];
  repairTypes: RepairType[];
  priceGroups: PriceGroup[];
};

const HEADER = `/**
 * GENERATED by scripts/generate-constants.ts from the Sanity dataset.
 *
 * Phase 6.9 moved this out of Sanity under Rule 1: if the shop owner will not
 * edit it, it does not belong in a CMS. Nine brands and sixteen repair types
 * do not change, and having them as documents meant every price row carried
 * two references that had to be resolved on every query.
 *
 * Regenerate only if the dataset is still the source of truth. After the
 * migration it is not: this file is.
 */
`;

function ts(value: unknown): string {
  return JSON.stringify(value, null, 2)
    .split("\n")
    .map((line, index) => (index === 0 ? line : `  ${line}`))
    .join("\n");
}

/* ------------------------------------------------------------------ brands */

const brands = `${HEADER}
import type { PortableTextBlock } from "@portabletext/types";

export type BrandType = "phone" | "tablet" | "computer";

export interface BrandDef {
  slug: string;
  name: string;
  type: BrandType;
  /** Display order on the price list and the home brand strip. */
  order: number;
  active: boolean;
  /** Rendered on the brand hub. Kept as portable text so the output is unchanged. */
  intro?: PortableTextBlock[];
  seoTitle?: string;
  seoDescription?: string;
}

export const BRANDS: BrandDef[] = ${ts(
  dump.brands.map((brand) => ({
    slug: brand.slug,
    name: brand.name,
    type: brand.type,
    order: brand.order,
    active: brand.active,
    ...(brand.intro ? { intro: brand.intro } : {}),
    ...(brand.seoTitle ? { seoTitle: brand.seoTitle } : {}),
    ...(brand.seoDescription ? { seoDescription: brand.seoDescription } : {}),
  })),
)} as BrandDef[];

const BY_SLUG = new Map(BRANDS.map((brand) => [brand.slug, brand]));

export function brand(slug: string): BrandDef | undefined {
  return BY_SLUG.get(slug);
}

export function activeBrands(): BrandDef[] {
  return BRANDS.filter((entry) => entry.active).sort((a, b) => a.order - b.order);
}
`;

/* ------------------------------------------------------------ repair types */

const repairTypes = `${HEADER}
import type { PortableTextBlock } from "@portabletext/types";

/** The device kinds a repair can apply to. */
export type DeviceKind = "phone" | "tablet" | "laptop";

/**
 * The repair slugs, as a union. This is what deviceModel.repairs references
 * now that priceEntry is gone, so a typo in a price row is a type error rather
 * than a dangling reference.
 */
export type RepairSlug = ${dump.repairTypes.map((entry) => `"${entry.slug}"`).join(" | ")};

export interface RepairTypeDef {
  slug: RepairSlug;
  name: string;
  icon?: string;
  shortDescription?: string;
  longDescription?: PortableTextBlock[];
  estimatedMinutes?: number;
  appliesTo: DeviceKind[];
  symptoms?: string[];
  order: number;
}

export const REPAIR_TYPES: RepairTypeDef[] = ${ts(
  dump.repairTypes.map((entry, index) => ({
    slug: entry.slug,
    name: entry.name,
    ...(entry.icon ? { icon: entry.icon } : {}),
    ...(entry.shortDescription ? { shortDescription: entry.shortDescription } : {}),
    ...(entry.longDescription ? { longDescription: entry.longDescription } : {}),
    ...(entry.estimatedMinutes ? { estimatedMinutes: entry.estimatedMinutes } : {}),
    appliesTo: entry.appliesTo ?? [],
    ...(entry.symptoms?.length ? { symptoms: entry.symptoms } : {}),
    order: entry.order ?? (index + 1) * 10,
  })),
)} as RepairTypeDef[];

const BY_SLUG = new Map(REPAIR_TYPES.map((entry) => [entry.slug, entry]));

export function repairType(slug: string): RepairTypeDef | undefined {
  return BY_SLUG.get(slug as RepairSlug);
}

/** Whether a string is one of the known repair slugs. */
export function isRepairSlug(slug: string): slug is RepairSlug {
  return BY_SLUG.has(slug as RepairSlug);
}

/** Repairs that apply to a device kind, in display order. */
export function repairsFor(kind: DeviceKind): RepairTypeDef[] {
  return REPAIR_TYPES.filter((entry) => entry.appliesTo.includes(kind)).sort(
    (a, b) => a.order - b.order,
  );
}

/**
 * Models that share one printed price.
 *
 * Was the priceGroup document type. It is a rendering concern: the note is
 * shown on a model page so a visitor understands why the iPhone 5, 5S and 5C
 * all cost the same. Nothing edits this.
 */
export interface PriceGroupDef {
  name: string;
  note?: string;
  models: string[];
}

export const PRICE_GROUPS: PriceGroupDef[] = ${ts(dump.priceGroups)} as PriceGroupDef[];

export function priceGroupFor(modelSlug: string): PriceGroupDef | undefined {
  return PRICE_GROUPS.find((group) => group.models.includes(modelSlug));
}
`;

writeFileSync("lib/content/brands.ts", brands, "utf8");
writeFileSync("lib/content/repair-types.ts", repairTypes, "utf8");

console.log(
  `Wrote lib/content/brands.ts (${dump.brands.length} brands) and ` +
    `lib/content/repair-types.ts (${dump.repairTypes.length} repair types, ` +
    `${dump.priceGroups.length} price groups)`,
);
