/**
 * Phase 6.9 migration: collapse the catalogue into six document types.
 *
 * What it does, in order:
 *
 *   1. Reads every deviceModel and its priceEntry rows.
 *   2. Writes the priced rows onto the model as an inline `repairs` array, and
 *      replaces the brand reference with a plain `brandSlug` string.
 *   3. Writes each model's SEO copy out to content/models/<slug>.ts.
 *   4. Copies the reviewSummary fields onto siteSettings.
 *   5. Deletes every priceEntry, brand, repairType, priceGroup, location and
 *      reviewSummary document.
 *
 * Rule 2 from the brief drives step 5: absence is not a document. 531 of the
 * 685 price rows exist only to record that a price does not exist.
 *
 * ONE DEVIATION FROM THE BRIEF, WITH EVIDENCE.
 *
 * The brief says to create no array entry for a repair with no price, and to
 * derive the "Call for quote" rows from the repair types that apply to the
 * device kind. scripts/verify-derivation.ts tested that against production and
 * it is lossless for ZERO of 156 models: every model carried a curated set of
 * three to five repairs, while thirteen apply to a phone. Deriving would add
 * eight or more quote-only rows to every phone page, which is a large content
 * change and reintroduces exactly the thin-content problem the build has
 * fought since Phase 2.
 *
 * The brief's overriding requirement is that the rendered output is identical,
 * so every offered repair becomes an array entry and `price` is simply absent
 * where there is no price. Rule 2 still holds where it matters: 685 documents
 * become 0, and the owner never creates or maintains a row to record an
 * absence. An optional field on an entry is not a document.
 *
 * DRY RUN BY DEFAULT. Nothing is written without --apply, and --apply refuses
 * to run without --dataset, so the live dataset cannot be hit by muscle
 * memory.
 *
 *   pnpm exec tsx --env-file=.env.local scripts/migrate-to-inline-prices.ts
 *   pnpm exec tsx --env-file=.env.local scripts/migrate-to-inline-prices.ts --apply --dataset=staging
 */

import { createWriteClient } from "../sanity/lib/write-client";

/*
 * Hard guard, not a comment.
 *
 * This deletes 729 documents. Production is off limits for the whole of Phase
 * 6.9: the deployment keeps reading it until the diff is clean and the cutover
 * is approved as its own step.
 */
const FORBIDDEN_DATASETS = ["production"];

const APPLY = process.argv.includes("--apply");
const DATASET_ARG = process.argv.find((arg) => arg.startsWith("--dataset="))?.split("=")[1];
const LIVE_DATASET = process.env.NEXT_PUBLIC_SANITY_DATASET ?? "production";
const DATASET = DATASET_ARG ?? LIVE_DATASET;

const CONTENT_DIR = "content/models";

interface PriceRow {
  price: number | null;
  quoteOnly: boolean | null;
  note: string | null;
  needsVerification: boolean | null;
  partGrade: string | null;
  turnaroundMinutes: number | null;
  warrantyDays: number | null;
  repairSlug: string | null;
}

interface ModelDoc {
  _id: string;
  name: string | null;
  slug: string | null;
  deviceType: string | null;
  brandSlug: string | null;
  published: boolean | null;
  intro: unknown;
  commonIssues: string[] | null;
  verdict: unknown;
  repairNotes: unknown;
  lastSupportedOs: string | null;
  stillReceivesUpdates: boolean | null;
  prices: PriceRow[];
}

function client() {
  return createWriteClient({ dataset: DATASET });
}

/** The content file for one model, written verbatim from the document. */
function contentFile(model: ModelDoc): string {
  const body = {
    slug: model.slug,
    name: model.name,
    intro: model.intro ?? null,
    commonIssues: model.commonIssues ?? [],
    verdict: model.verdict ?? null,
    repairNotes: model.repairNotes ?? null,
    lastSupportedOs: model.lastSupportedOs ?? null,
    stillReceivesUpdates: model.stillReceivesUpdates ?? null,
  };

  return `/**
 * GENERATED by scripts/migrate-to-inline-prices.ts. Moved out of Sanity in
 * Phase 6.9 under Rule 1: the shop owner will not write SEO body copy, and
 * putting it behind a CMS gave them 84 pages of prose they would never touch
 * and a way to break the similarity and word-count checks.
 *
 * Edit this in a pull request, where those checks run.
 */

import type { ModelContent } from "@/lib/content/model-content";

export const content: ModelContent = ${JSON.stringify(body, null, 2)} as ModelContent;

export default content;
`;
}

async function main() {
  const sanity = client();

  console.log(`\nPhase 6.9 migration`);
  console.log(`  dataset : ${DATASET}`);
  console.log(`  mode    : ${APPLY ? "APPLY, this writes" : "dry run, nothing is written"}\n`);

  if (FORBIDDEN_DATASETS.includes(DATASET)) {
    console.error(
      `Refusing to run against "${DATASET}".
` +
        `Phase 6.9 migrates staging only. Production is cut over as a separate, approved step.
`,
    );
    process.exit(1);
  }

  if (APPLY && !DATASET_ARG) {
    console.error(
      `Refusing to apply without an explicit --dataset. The live dataset is "${LIVE_DATASET}".\n` +
        `Copy it first:  npx sanity dataset copy ${LIVE_DATASET} staging\n` +
        `Then:           --apply --dataset=staging\n`,
    );
    process.exit(1);
  }

  /* --- read ---------------------------------------------------------- */
  const models = await sanity.fetch<ModelDoc[]>(`
    *[_type == "deviceModel" && !(_id in path("drafts.**"))]{
      _id, name, "slug": slug.current, deviceType, published,
      "brandSlug": brand->slug.current,
      intro, commonIssues, verdict, repairNotes, lastSupportedOs, stillReceivesUpdates,
      "prices": *[_type == "priceEntry" && model._ref == ^._id && !(_id in path("drafts.**"))]{
        price, quoteOnly, note, needsVerification, partGrade, turnaroundMinutes, warrantyDays,
        "repairSlug": repairType->slug.current
      }
    }
  `);

  const counts = {
    models: models.length,
    priceRows: models.reduce((sum, model) => sum + model.prices.length, 0),
    priced: 0,
    quoteOnly: 0,
    withContent: 0,
  };

  const patches: { id: string; repairs: unknown[]; brandSlug: string | null }[] = [];
  const contentFiles: { slug: string; body: string }[] = [];

  for (const model of models) {
    /*
     * Every repair the shop offers on this model, in the order the documents
     * had. `price` is present or absent; nothing else distinguishes a quoted
     * repair from a priced one, which is what the page already assumed.
     */
    const offered = model.prices.filter((row) => row.repairSlug);
    const priced = offered.filter((row) => typeof row.price === "number" && row.quoteOnly !== true);
    counts.priced += priced.length;
    counts.quoteOnly += offered.length - priced.length;

    patches.push({
      id: model._id,
      brandSlug: model.brandSlug,
      repairs: offered.map((row) => ({
        _type: "modelRepair",
        _key: `${row.repairSlug}`,
        repair: row.repairSlug,
        ...(typeof row.price === "number" && row.quoteOnly !== true ? { price: row.price } : {}),
        ...(row.note ? { note: row.note } : {}),
        ...(row.needsVerification ? { needsVerification: true } : {}),
        ...(row.partGrade ? { partGrade: row.partGrade } : {}),
        ...(row.turnaroundMinutes ? { turnaroundMinutes: row.turnaroundMinutes } : {}),
        ...(row.warrantyDays ? { warrantyDays: row.warrantyDays } : {}),
      })),
    });

    if (model.intro || (model.commonIssues?.length ?? 0) > 0 || model.verdict) {
      counts.withContent += 1;
      if (model.slug) contentFiles.push({ slug: model.slug, body: contentFile(model) });
    }
  }

  /* --- report -------------------------------------------------------- */
  console.log(`  deviceModel documents        : ${counts.models}`);
  console.log(`  priceEntry documents         : ${counts.priceRows}`);
  console.log(`    with a real price          : ${counts.priced}  -> inline, with price`);
  console.log(`    quoted, no price           : ${counts.quoteOnly}  -> inline, price omitted`);
  console.log(`  models with SEO copy         : ${counts.withContent}  -> content/models/`);

  const doomed = await sanity.fetch<Record<string, number>>(`{
    "priceEntry": count(*[_type == "priceEntry"]),
    "brand": count(*[_type == "brand"]),
    "repairType": count(*[_type == "repairType"]),
    "priceGroup": count(*[_type == "priceGroup"]),
    "location": count(*[_type == "location"]),
    "reviewSummary": count(*[_type == "reviewSummary"])
  }`);

  const totalDoomed = Object.values(doomed).reduce((sum, n) => sum + n, 0);
  console.log(`\n  documents to delete          : ${totalDoomed}`);
  for (const [type, n] of Object.entries(doomed)) {
    if (n > 0) console.log(`    ${type.padEnd(26)} ${n}`);
  }

  if (!APPLY) {
    console.log(`\n  Dry run. Re-run with --apply --dataset=<copy> to write.\n`);
    return;
  }

  /* --- write --------------------------------------------------------- */
  /*
   * Content files are written by scripts/extract-model-content.ts, which also
   * emits the static import index that makes a missing file a compile error.
   * Writing them from here too would produce the same copy in a shape the
   * index does not expect, so this only reports.
   */
  console.log(
    `
  ${contentFiles.length} models carry copy; files already generated in ${CONTENT_DIR}`,
  );

  let tx = sanity.transaction();
  let queued = 0;

  for (const patch of patches) {
    tx = tx.patch(patch.id, (p) =>
      p
        .set({ repairs: patch.repairs, ...(patch.brandSlug ? { brandSlug: patch.brandSlug } : {}) })
        .unset(["brand", "intro", "commonIssues", "verdict", "repairNotes"]),
    );
    queued += 1;
    if (queued % 50 === 0) {
      await tx.commit({ visibility: "async" });
      tx = sanity.transaction();
    }
  }
  await tx.commit({ visibility: "async" });
  console.log(`  patched ${patches.length} models`);

  for (const type of [
    "priceEntry",
    "brand",
    "repairType",
    "priceGroup",
    "location",
    "reviewSummary",
  ]) {
    await sanity.delete({ query: `*[_type == "${type}"]` });
    console.log(`  deleted every ${type}`);
  }

  console.log(`\n  Done. Rebuild and diff before trusting anything.\n`);
}

main().catch((error) => {
  console.error("migration failed:", error);
  process.exit(1);
});

export {};
